import { describe, expect, it } from 'vitest';
import {
  isImportConflict,
  matchingCommandNames,
  parseConflictedCommandNames,
  parseImportConflictLabels,
} from './command-conflicts';

describe('parseConflictedCommandNames', () => {
  it('reads every /name from a grouped unstamped error', () => {
    expect(
      parseConflictedCommandNames(
        'Command files exist and were not generated by skil (/testing, /review). Re-export with replace to overwrite.'
      )
    ).toEqual(['testing', 'review']);
  });

  it('reads a single-path leftover error', () => {
    expect(
      parseConflictedCommandNames(
        "Command file '.cursor/commands/frontend.md' exists and was not generated by skil. Re-export with replace to overwrite."
      )
    ).toEqual(['frontend']);
  });
});

describe('parseImportConflictLabels', () => {
  it('reads skills and commands from an import replace error', () => {
    expect(
      parseImportConflictLabels(
        'Import would overwrite existing skills (tdd, ui/styling) and existing commands (/build). Re-import with replace to overwrite.'
      )
    ).toEqual(['tdd', 'ui/styling', '/build']);
  });

  it('reads unstamped command files too', () => {
    expect(
      parseImportConflictLabels(
        'Import would overwrite command files that were not generated by skil (/planning). Re-import with replace to overwrite.'
      )
    ).toEqual(['/planning']);
  });
});

describe('isImportConflict', () => {
  it('is true for import replace errors and unstamped leftovers', () => {
    expect(isImportConflict('Import would overwrite existing skills (tdd). Re-import with replace to overwrite.')).toBe(
      true
    );
    expect(isImportConflict('Command files exist and were not generated by skil (/build).')).toBe(true);
    expect(isImportConflict('Nothing to import from /tmp/other for cursor')).toBe(false);
  });
});

describe('matchingCommandNames', () => {
  it('returns source names that already exist on the dest workspace', () => {
    expect(
      matchingCommandNames(
        [{ name: 'build' }, { name: 'review' }, { name: 'testing' }],
        [{ name: 'build' }, { name: 'testing' }]
      )
    ).toEqual(['build', 'testing']);
  });
});
