/** Names inside `not generated by skil (/build, /test).` */
const GROUPED_NAMES = /not generated by skil \(([^)]+)\)/i;
/** Fallback for a single-path engine error. */
const SINGLE_PATH = /Command file '([^']+)' exists/i;

export function parseConflictedCommandNames(message: string): string[] {
  const grouped = message.match(GROUPED_NAMES);
  if (grouped?.[1]) {
    return grouped[1]
      .split(',')
      .map((part) => part.trim().replace(/^\//, ''))
      .filter(Boolean);
  }
  const single = message.match(SINGLE_PATH);
  if (!single?.[1]) return [];
  const file = single[1].replace(/\\/g, '/').split('/').pop() ?? '';
  return file.endsWith('.md') ? [file.slice(0, -3)] : [];
}

export function matchingCommandNames(
  source: Array<{ name: string }>,
  dest: Array<{ name: string }>
): string[] {
  const destNames = new Set(dest.map((command) => command.name));
  return source.map((command) => command.name).filter((name) => destNames.has(name));
}
