import { describe, expect, it } from 'vitest';
import { matchingCommandNames, parseConflictedCommandNames } from './command-conflicts';

describe('parseConflictedCommandNames', () => {
  it('reads every /name from a grouped unstamped error', () => {
    expect(
      parseConflictedCommandNames(
        'Command files exist and were not generated by skil (/testing, /review). Re-export with replace to overwrite.'
      )
    ).toEqual(['testing', 'review']);
  });

  it('reads a single-path leftover error', () => {
    expect(
      parseConflictedCommandNames(
        "Command file '.cursor/commands/frontend.md' exists and was not generated by skil. Re-export with replace to overwrite."
      )
    ).toEqual(['frontend']);
  });
});

describe('matchingCommandNames', () => {
  it('returns source names that already exist on the dest workspace', () => {
    expect(
      matchingCommandNames(
        [{ name: 'build' }, { name: 'review' }, { name: 'testing' }],
        [{ name: 'build' }, { name: 'testing' }]
      )
    ).toEqual(['build', 'testing']);
  });
});
