import { createHash } from 'node:crypto';
import type { ICollectionEngine } from '../interfaces/engine.js';
import type { IFileSystemAdapter, ISkillsAdapter, IUsageCollector } from '../interfaces/adapters.js';
import type {
  BrowseView,
  Collection,
  Command,
  CommandRecord,
  ExportResult,
  IDE,
  OriginCheck,
  RuleRecord,
  ScanResult,
  Skill,
  SkillRecord,
  State,
  UsageRow,
} from '../types/index.js';
import { err, isOk, ok, type Result } from './result.js';
import { isClosedSkilStamp, isSkilStamped, parseStampedSkills, writeCommandFile } from './command-file.js';
import {
  canToggleAlwaysApply,
  collapseRules,
  collectRules,
  destRuleTargets,
  importRulePathsForDock,
  readRuleSection,
  ruleBodiesEqual,
  stampRule,
  upsertRuleSection,
  withAlwaysApply,
} from './project-rules.js';
import {
  COMMAND_DIR_BY_IDE,
  COMMAND_EXTENSION_BY_IDE,
  LIVE_IDES,
  liveSkillPaths,
  SCAN_SKILL_ROOTS,
  SKILL_ROOTS,
  SKILL_ROOT_BY_IDE,
} from './dock-layout.js';

/** Path to the persisted engine state, relative to the project root. */
export const STATE_PATH = '.skil/state.json';

const LEFTOVER_STATE_PATH = '.contextkit/state.json';

/** Current state schema version. See `State`'s doc comment for the v5 → v6 notes. */
const STATE_VERSION = '6.0';

const DEFAULT_IDE: IDE = 'cursor';

const ALL_IDES: IDE[] = ['cursor', 'claude', 'codex', 'copilot', 'agents', 'windsurf'];

/** Command name reserved for the Inbox holding list on `State`. */
const INBOX_NAME = 'inbox';

/** Store `/build` as `build`. UI may still display the slash. */
function normalizeCommandName(name: string): string {
  return name.startsWith('/') ? name.slice(1) : name;
}

function commandNotFound(name: string): Error {
  return new Error(`Command '${name}' not found. Run 'skil list' to see available commands.`);
}

function skillFolderName(skillId: string): string {
  return skillId.split('/').filter(Boolean).at(-1) ?? skillId;
}

function commandDir(ide: IDE): string | undefined {
  return COMMAND_DIR_BY_IDE[ide];
}

function commandExtension(ide: IDE): string {
  return COMMAND_EXTENSION_BY_IDE[ide] ?? '.md';
}

/** Prefix a workspace-relative path with an optional dest root. */
function underRoot(root: string | undefined, relative: string): string {
  if (!root) return relative;
  return `${root.replace(/\\/g, '/').replace(/\/+$/, '')}/${relative}`;
}

function commandFilePath(ide: IDE, name: string, dest?: string): string | undefined {
  const dir = commandDir(ide);
  if (!dir) return undefined;
  return underRoot(dest, `${dir}/${name}${commandExtension(ide)}`);
}

function unstampedConflict(conflicts: Array<{ name: string; path: string }>): Result<never> {
  const labels = conflicts.map((conflict) => conflict.name);
  const names = labels.map((name) => `/${name}`).join(', ');
  return err(
    new Error(
      `Command files exist and were not generated by skil (${names}). Re-export with replace to overwrite.`
    ),
    { code: 'UNSTAMPED_COMMAND', labels }
  );
}

function importConflict(
  skills: string[],
  commands: string[],
  unstamped: string[],
  rules: string[] = []
): Result<never> {
  const parts: string[] = [];
  if (skills.length > 0) {
    parts.push(`existing skills (${skills.join(', ')})`);
  }
  if (commands.length > 0) {
    parts.push(`existing commands (${commands.map((name) => `/${name}`).join(', ')})`);
  }
  if (unstamped.length > 0) {
    parts.push(`command files that were not generated by skil (${unstamped.map((name) => `/${name}`).join(', ')})`);
  }
  if (rules.length > 0) {
    parts.push(`existing rules (${rules.join(', ')})`);
  }
  const labels = [
    ...skills,
    ...commands.map((name) => `/${name}`),
    ...unstamped.map((name) => `/${name}`),
    ...rules,
  ];
  return err(new Error(`Import would overwrite ${parts.join(' and ')}. Re-import with replace to overwrite.`), {
    code: 'IMPORT_CONFLICT',
    labels,
  });
}

function normalizeFsPath(path: string): string {
  return path.replace(/\\/g, '/').replace(/\/+$/, '');
}

function skillIdFromFolder(folder: string, skillRoot: string): string {
  const normalized = normalizeFsPath(folder);
  const marker = `${skillRoot}/`;
  const index = normalized.lastIndexOf(marker);
  if (index === -1) {
    return normalized === skillRoot || normalized.endsWith(`/${skillRoot}`) ? '.' : '';
  }
  return normalized.slice(index + marker.length);
}

/** On-disk command that may still use v4 `skills[]`. */
interface PersistedCommand {
  name: string;
  skills?: string[];
  membership?: Partial<Record<IDE, string[]>>;
  createdAt: string;
  command?: string;
}

/** On-disk shape that may still use v3 `collections`. */
interface PersistedState {
  version?: string;
  commands?: PersistedCommand[];
  collections?: PersistedCommand[];
  skills?: SkillRecord[];
  inbox?: string[];
  installedSkills?: Skill[];
}

function emptyState(): State {
  return { commands: [], skills: [], installedSkills: [], inbox: [], version: STATE_VERSION };
}

function unionMembership(membership: Partial<Record<IDE, string[]>>): string[] {
  const seen = new Set<string>();
  const skills: string[] = [];
  const order: IDE[] = [DEFAULT_IDE, ...ALL_IDES.filter((ide) => ide !== DEFAULT_IDE)];
  for (const ide of order) {
    for (const id of membership[ide] ?? []) {
      if (!seen.has(id)) {
        seen.add(id);
        skills.push(id);
      }
    }
  }
  return skills;
}

function toCommandRecord(raw: PersistedCommand): CommandRecord {
  const skills =
    raw.membership !== undefined ? unionMembership(raw.membership) : [...(raw.skills ?? [])];
  return {
    name: raw.name,
    skills,
    createdAt: raw.createdAt,
    ...(raw.command !== undefined ? { command: raw.command } : {}),
  };
}

function normalizeState(raw: PersistedState): State {
  const commands = (raw.commands ?? raw.collections ?? []).map(toCommandRecord);
  return {
    commands,
    skills: raw.skills ?? [],
    installedSkills: raw.installedSkills ?? [],
    inbox: raw.inbox ?? [],
    version: raw.version ?? STATE_VERSION,
  };
}

function toView(record: CommandRecord): Command {
  return {
    name: record.name,
    skills: [...record.skills],
    createdAt: record.createdAt,
    ...(record.command !== undefined ? { command: record.command } : {}),
  };
}

function cloneCommandRecord(record: CommandRecord): CommandRecord {
  return {
    ...record,
    skills: [...record.skills],
  };
}

/** Load `.skil/state.json`. Missing file → empty state. Leftover `.contextkit/state.json` with no `.skil/` file is an error. */
function loadState(fs: IFileSystemAdapter): State {
  const current = fs.readJSON<PersistedState>(STATE_PATH);
  if (isOk(current)) {
    return normalizeState(current.value);
  }
  const leftover = fs.readJSON<PersistedState>(LEFTOVER_STATE_PATH);
  if (isOk(leftover)) {
    throw new Error(
      'Found leftover .contextkit/state.json. Move it to .skil/state.json and retry.'
    );
  }
  return emptyState();
}

/**
 * CollectionEngine is skil's deep module: see ICollectionEngine for the
 * public contract. This class owns state management, validation, and
 * coordination with the injected adapters.
 */
const NOOP_USAGE: IUsageCollector = {
  async collect() {
    return ok([]);
  },
};

export class CollectionEngine implements ICollectionEngine {
  private state: State;
  private writtenPaths: string[] = [];

  constructor(
    private readonly fs: IFileSystemAdapter,
    private readonly skillsAdapter: ISkillsAdapter,
    private readonly usageCollector: IUsageCollector = NOOP_USAGE,
    private readonly projectRoot: string = process.cwd()
  ) {
    this.state = loadState(this.fs);
    this.mergeExternallyInstalledSkills();
  }

  lastWrittenPaths(): string[] {
    return [...this.writtenPaths];
  }

  async usage(): Promise<Result<UsageRow[]>> {
    const skillIds = this.state.skills.map((skill) => skill.id);
    const collected = await this.usageCollector.collect({
      projectRoot: this.projectRoot,
      skillIds,
    });
    if (!isOk(collected)) {
      return err(collected.error);
    }
    const counts = new Map<string, number>();
    for (const event of collected.value) {
      counts.set(event.skillId, (counts.get(event.skillId) ?? 0) + 1);
    }
    const rows = [...counts.entries()]
      .map(([skillId, count]) => ({ skillId, count }))
      .sort((a, b) => b.count - a.count || a.skillId.localeCompare(b.skillId));
    return ok(rows);
  }

  create(name: string, skillIds: string[], command?: string, _ide?: IDE): Result<Collection> {
    name = normalizeCommandName(name);
    if (name === INBOX_NAME) {
      return err(new Error(`'inbox' is not a command. Inbox is a holding list of skill IDs — add with 'skil inbox add' and file them onto a named command.`));
    }

    const existing = this.state.commands.find((c) => c.name === name);
    if (existing) {
      return err(new Error(`Command '${name}' already exists. Choose a different name or run 'skil list' to see existing commands.`));
    }

    const record: CommandRecord = {
      name,
      skills: [...skillIds],
      createdAt: new Date().toISOString(),
      ...(command !== undefined ? { command } : {}),
    };
    this.state.commands.push(record);
    const persistResult = this.persist();
    if (!isOk(persistResult)) {
      this.state.commands.pop();
      return err(new Error(`Failed to save command '${name}': ${persistResult.error.message}`));
    }

    this.writeThroughExisting([name]);
    return ok(toView(record));
  }

  addSkill(name: string, skillId: string, _ide?: IDE): Result<Collection> {
    name = normalizeCommandName(name);
    const record = this.state.commands.find((c) => c.name === name);
    if (!record) {
      return err(commandNotFound(name));
    }
    if (record.skills.includes(skillId)) {
      return ok(toView(record));
    }

    const snapshot = [...record.skills];
    record.skills.push(skillId);
    const persistResult = this.persist();
    if (!isOk(persistResult)) {
      record.skills = snapshot;
      return err(new Error(`Failed to save command '${name}': ${persistResult.error.message}`));
    }

    this.writeThroughExisting([name]);
    return ok(toView(record));
  }

  removeSkill(name: string, skillId: string, _ide?: IDE): Result<Collection> {
    name = normalizeCommandName(name);
    const record = this.state.commands.find((c) => c.name === name);
    if (!record) {
      return err(commandNotFound(name));
    }

    const index = record.skills.indexOf(skillId);
    if (index === -1) {
      return ok(toView(record));
    }

    const snapshot = [...record.skills];
    record.skills.splice(index, 1);
    const persistResult = this.persist();
    if (!isOk(persistResult)) {
      record.skills = snapshot;
      return err(new Error(`Failed to save command '${name}': ${persistResult.error.message}`));
    }

    this.writeThroughExisting([name]);
    return ok(toView(record));
  }

  list(_ide?: IDE): Collection[] {
    return this.state.commands.map((c) => toView(c));
  }

  async install(
    skillId: string,
    opts?: { dest?: string; replace?: boolean; refreshOrigin?: boolean }
  ): Promise<Result<SkillRecord>> {
    const livePaths = liveSkillPaths(skillId).map((path) => underRoot(opts?.dest, path));
    const [agentsPath, ...mirrorPaths] = livePaths as [string, ...string[]];

    const result = await this.skillsAdapter.install(skillId, opts?.dest ? { cwd: opts.dest } : undefined);
    if (!isOk(result)) {
      return err(result.error);
    }

    const placed = this.relocateNpxInstall(skillId, opts?.dest, opts?.replace === true);
    if (!isOk(placed)) {
      return placed;
    }

    for (const mirrorPath of mirrorPaths) {
      const mirrored = this.mirrorLiveInstall(skillId, agentsPath, mirrorPath, opts?.replace === true);
      if (!isOk(mirrored)) {
        return mirrored;
      }
    }

    const installedAt = new Date().toISOString();
    const existingIndex = this.state.skills.findIndex((s) => s.id === skillId);
    const previous = existingIndex >= 0 ? cloneSkillRecord(this.state.skills[existingIndex]) : undefined;
    const hash = hashSkillAt(this.fs, agentsPath) ?? previous?.hash ?? '';
    const originHash = opts?.refreshOrigin
      ? hash || previous?.originHash
      : previous?.originHash ?? (hash || undefined);

    const deploys = LIVE_IDES.map((ide, index) => ({
      ide,
      path: livePaths[index] as string,
      installedAt,
    }));

    const record: SkillRecord = previous
      ? {
          ...previous,
          hash,
          ...(originHash !== undefined ? { originHash } : {}),
          paths: [...previous.paths, ...livePaths.filter((path) => !previous.paths.includes(path))],
          deployedTo: deploys.reduce(upsertDeploy, previous.deployedTo),
        }
      : {
          id: skillId,
          hash,
          ...(hash ? { originHash: hash } : {}),
          paths: [...livePaths],
          deployedTo: deploys,
          source: 'skills.sh',
        };

    if (existingIndex >= 0) {
      this.state.skills[existingIndex] = record;
    } else {
      this.state.skills.push(record);
    }

    const persistResult = this.persist();
    if (!isOk(persistResult)) {
      if (previous && existingIndex >= 0) {
        this.state.skills[existingIndex] = previous;
      } else {
        this.state.skills.pop();
      }
      return err(new Error(`Failed to save installed skill '${skillId}': ${persistResult.error.message}`));
    }

    this.writtenPaths = livePaths.flatMap((path) => [path, `${path}/SKILL.md`]);
    return ok(record);
  }

  search(query: string): Promise<Result<Skill[]>> {
    return this.skillsAdapter.search(query);
  }

  browse(view: BrowseView): Promise<Result<Skill[]>> {
    return this.skillsAdapter.browse(view);
  }

  async exportCommand(
    name: string,
    targetIDE: IDE,
    opts?: { replace?: boolean; dest?: string; body?: string }
  ): Promise<Result<ExportResult>> {
    name = normalizeCommandName(name);
    const command = this.state.commands.find((c) => c.name === name);
    if (!command) {
      return err(commandNotFound(name));
    }

    const skills = command.skills;
    const path = commandFilePath(targetIDE, name, opts?.dest);
    const succeeded: string[] = [];
    const writtenPaths: string[] = [];

    if (path) {
      const existing = this.fs.readFile(path);
      if (isOk(existing) && !isSkilStamped(existing.value) && opts?.replace !== true) {
        return unstampedConflict([{ name, path }]);
      }

      const seed = opts?.body ?? (isOk(existing) ? existing.value : undefined);
      const written = this.fs.writeFile(
        path,
        writeCommandFile(name, skills, seed, {
          reset: opts?.replace === true && opts?.body === undefined,
        })
      );
      if (!isOk(written)) {
        return err(new Error(`Failed to write command file '${path}': ${written.error.message}`));
      }
      writtenPaths.push(path);
      succeeded.push(path);
    }

    this.writtenPaths = writtenPaths;
    const failures: string[] = [];
    let copied = false;

    for (const skillId of skills) {
      const skillFolder = underRoot(opts?.dest, `${SKILL_ROOT_BY_IDE[targetIDE]}/${skillId}`);
      if (isOk(this.fs.readFile(`${skillFolder}/SKILL.md`))) {
        continue;
      }

      const record = this.state.skills.find((skill) => skill.id === skillId);
      let source = record?.paths.find(
        (folder) => folder !== skillFolder && isOk(this.fs.readFile(`${folder}/SKILL.md`))
      );

      if (!source) {
        // Discover-only id: install writes the live pair, then the dest
        // dock (if it is not one of the live trees) is copied from there.
        const installed = await this.install(skillId, opts?.dest ? { dest: opts.dest } : undefined);
        if (!isOk(installed)) {
          failures.push(`'${skillId}': ${installed.error.message}`);
          continue;
        }
        if (isOk(this.fs.readFile(`${skillFolder}/SKILL.md`))) {
          succeeded.push(skillFolder);
          continue;
        }
        source = installed.value.paths.find(
          (folder) => folder !== skillFolder && isOk(this.fs.readFile(`${folder}/SKILL.md`))
        );
        if (!source) {
          // Adapter reported success but delivered no folder (in-memory
          // doubles): trust it, same as the pre-pivot install path did.
          succeeded.push(skillFolder);
          continue;
        }
      }

      const copyResult = this.fs.copyDir(source, skillFolder);
      if (!isOk(copyResult)) {
        failures.push(`'${skillId}': ${copyResult.error.message}`);
        continue;
      }
      this.recordLocalDeploy(skillId, targetIDE, skillFolder);
      succeeded.push(skillFolder);
      copied = true;
    }

    if (copied) {
      const persistResult = this.persist();
      if (!isOk(persistResult)) {
        failures.push(`Failed to save skill deploys: ${persistResult.error.message}`);
      }
    }

    return ok({ succeeded, failures });
  }

  async exportAll(
    targetIDE: IDE,
    opts?: { replace?: boolean; dest?: string }
  ): Promise<Result<ExportResult>> {
    const commands = this.state.commands;
    if (commands.length === 0) {
      return err(new Error('No commands to export'));
    }

    if (opts?.replace !== true) {
      const conflicts = this.unstampedConflicts(
        commands.map((command) => command.name),
        targetIDE,
        opts?.dest
      );
      if (conflicts.length > 0) {
        return unstampedConflict(conflicts);
      }
    }

    const succeeded: string[] = [];
    const failures: string[] = [];
    for (const command of commands) {
      const result = await this.exportCommand(command.name, targetIDE, opts);
      if (!isOk(result)) {
        return result;
      }
      succeeded.push(...result.value.succeeded);
      failures.push(...result.value.failures);
    }
    return ok({ succeeded, failures });
  }

  inbox(): string[] {
    return [...this.state.inbox];
  }

  addToInbox(skillId: string): Result<string[]> {
    if (this.state.inbox.includes(skillId)) {
      return ok(this.inbox());
    }

    this.state.inbox.push(skillId);
    const persistResult = this.persist();
    if (!isOk(persistResult)) {
      this.state.inbox.pop();
      return err(new Error(`Failed to save inbox: ${persistResult.error.message}`));
    }

    return ok(this.inbox());
  }

  removeFromInbox(skillId: string): Result<string[]> {
    const index = this.state.inbox.indexOf(skillId);
    if (index === -1) {
      return ok(this.inbox());
    }

    this.state.inbox.splice(index, 1);
    const persistResult = this.persist();
    if (!isOk(persistResult)) {
      this.state.inbox.splice(index, 0, skillId);
      return err(new Error(`Failed to save inbox: ${persistResult.error.message}`));
    }

    return ok(this.inbox());
  }

  deleteSkill(skillId: string): Result<void> {
    const record = this.state.skills.find((skill) => skill.id === skillId);
    const filed = this.commandsFiling(skillId);
    if (!record && !this.state.inbox.includes(skillId) && filed.length === 0) {
      return ok(undefined);
    }

    const snapshot = {
      skills: this.state.skills.map((skill) => ({
        ...skill,
        paths: [...skill.paths],
        deployedTo: skill.deployedTo.map((entry) => ({ ...entry })),
      })),
      inbox: [...this.state.inbox],
      commands: this.state.commands.map(cloneCommandRecord),
    };

    if (record) {
      this.state.skills = this.state.skills.filter((skill) => skill.id !== skillId);
    }
    this.dropSkillId(skillId);

    const persistResult = this.persist();
    if (!isOk(persistResult)) {
      this.state.skills = snapshot.skills;
      this.state.inbox = snapshot.inbox;
      this.state.commands = snapshot.commands;
      return err(new Error(`Failed to save after deleting '${skillId}': ${persistResult.error.message}`));
    }

    const muted: string[] = [];
    if (record) {
      for (const folder of record.paths) {
        if (!skillRootOf(folder)) {
          continue;
        }
        const removed = this.removeSkillFolder(folder);
        if (!isOk(removed)) {
          return err(removed.error);
        }
        muted.push(...removed.value);
      }
    }

    const names = [...new Set(filed.map((entry) => entry.name))];
    const written = names.length > 0 ? this.writeThroughExisting(names) : [];
    this.writtenPaths = [...muted, ...written];
    return ok(undefined);
  }

  readSkillMd(skillId: string): Result<string> {
    const record = this.state.skills.find((skill) => skill.id === skillId);
    if (!record) {
      return err(new Error(`Skill '${skillId}' is not in the catalog.`));
    }

    for (const folder of record.paths) {
      const contents = this.fs.readFile(`${folder}/SKILL.md`);
      if (isOk(contents)) {
        return ok(contents.value);
      }
    }

    return err(new Error(`Skill '${skillId}' has no SKILL.md on disk.`));
  }

  file(skillId: string, commandName: string, _ide?: IDE): Result<Collection> {
    commandName = normalizeCommandName(commandName);
    const record = this.state.commands.find((c) => c.name === commandName);
    if (!record) {
      return err(commandNotFound(commandName));
    }

    if (!this.state.inbox.includes(skillId)) {
      return err(new Error(`'${skillId}' is not in Inbox. Add it first, then file it onto a command.`));
    }

    const skillsSnapshot = [...record.skills];
    if (!record.skills.includes(skillId)) {
      record.skills.push(skillId);
    }

    const persistResult = this.persist();
    if (!isOk(persistResult)) {
      record.skills = skillsSnapshot;
      return err(new Error(`Failed to save command '${commandName}': ${persistResult.error.message}`));
    }

    this.writeThroughExisting([commandName]);
    return ok(toView(record));
  }

  delete(name: string, _ide?: IDE): Result<void> {
    name = normalizeCommandName(name);
    const index = this.state.commands.findIndex((c) => c.name === name);
    if (index === -1) {
      return err(commandNotFound(name));
    }

    const existing = this.state.commands[index];
    if (!existing) {
      return err(commandNotFound(name));
    }

    const snapshot = cloneCommandRecord(existing);
    this.state.commands.splice(index, 1);

    const persistResult = this.persist();
    if (!isOk(persistResult)) {
      this.state.commands.splice(index, 0, snapshot);
      return err(new Error(`Failed to save after deleting '${name}': ${persistResult.error.message}`));
    }

    this.writeThroughExisting([name]);
    return ok(undefined);
  }

  async copyTo(
    name: string,
    _fromIde: IDE,
    toIde: IDE,
    opts?: { replace?: boolean; dest?: string }
  ): Promise<Result<ExportResult>> {
    return this.exportCommand(name, toIde, opts);
  }

  async copyAll(
    _fromIde: IDE,
    toIde: IDE,
    opts?: { replace?: boolean; dest?: string }
  ): Promise<Result<ExportResult>> {
    return this.exportAll(toIde, opts);
  }

  async importFrom(
    sourceRoot: string,
    ide: IDE,
    opts?: { replace?: boolean }
  ): Promise<Result<ExportResult>> {
    const root = sourceRoot.replace(/\\/g, '/').replace(/\/+$/, '');
    if (root === '' || root === '.' || root === './') {
      return err(new Error('Cannot import a project into itself'));
    }

    const skillRoot = SKILL_ROOT_BY_IDE[ide];
    const dir = commandDir(ide);
    const sourceSkillRoot = underRoot(root, skillRoot);

    const folders = this.fs.findSkillFolders(sourceSkillRoot);
    if (!isOk(folders)) {
      return err(folders.error);
    }

    const sourceSkills: Array<{ id: string; folder: string; hash: string }> = [];
    for (const folder of folders.value) {
      const id = skillIdFromFolder(folder, skillRoot);
      if (id === '') {
        continue;
      }
      const destFolder = `${skillRoot}/${id}`;
      if (normalizeFsPath(folder) === normalizeFsPath(destFolder)) {
        return err(new Error('Cannot import a project into itself'));
      }
      const contents = this.fs.readFile(`${folder}/SKILL.md`);
      if (!isOk(contents)) {
        return err(contents.error);
      }
      sourceSkills.push({
        id,
        folder,
        hash: createHash('sha256').update(contents.value, 'utf8').digest('hex'),
      });
    }

    const listed = dir ? this.fs.listFiles(underRoot(root, dir)) : ok([]);
    if (!isOk(listed)) {
      return err(listed.error);
    }

    const ext = commandExtension(ide);
    const sourceCommands: Array<{ name: string; path: string; contents: string; skills: string[] }> = [];
    for (const path of listed.value) {
      if (!path.endsWith(ext)) {
        continue;
      }
      const name = path.slice(path.lastIndexOf('/') + 1, -ext.length);
      if (name === '') {
        continue;
      }
      const contents = this.fs.readFile(path);
      if (!isOk(contents) || !isSkilStamped(contents.value)) {
        continue;
      }
      sourceCommands.push({
        name,
        path,
        contents: contents.value,
        skills: parseStampedSkills(contents.value) ?? [],
      });
    }

    const allSourceRules = collectRules(this.fs, root);
    if (!isOk(allSourceRules)) {
      return allSourceRules;
    }
    const sourceRules = importRulePathsForDock(ide, allSourceRules.value);

    if (sourceSkills.length === 0 && sourceCommands.length === 0 && sourceRules.length === 0) {
      return err(new Error(`Nothing to import from ${root} for ${ide}`));
    }

    const skillConflicts: string[] = [];
    for (const skill of sourceSkills) {
      const destFolder = `${skillRoot}/${skill.id}`;
      const destHash = hashSkillAt(this.fs, destFolder);
      if (destHash !== undefined && destHash !== skill.hash) {
        skillConflicts.push(skill.id);
      }
    }

    const commandConflicts: string[] = [];
    const unstamped = this.unstampedConflicts(
      sourceCommands.map((command) => command.name),
      ide
    );
    const unstampedNames = new Set(unstamped.map((conflict) => conflict.name));
    for (const command of sourceCommands) {
      if (unstampedNames.has(command.name)) {
        continue;
      }
      const existing = this.state.commands.find((record) => record.name === command.name);
      const destSkills = existing?.skills;
      if (destSkills !== undefined && !listsEqual(destSkills, command.skills)) {
        commandConflicts.push(command.name);
      }
    }

    const ruleConflicts: string[] = [];
    for (const rule of sourceRules) {
      const src = this.fs.readFile(underRoot(root, rule.path));
      if (!isOk(src)) {
        continue;
      }
      const destHash = hashFileAt(this.fs, rule.path);
      const srcHash = createHash('sha256').update(src.value, 'utf8').digest('hex');
      if (destHash !== undefined && destHash !== srcHash) {
        ruleConflicts.push(rule.name);
      }
    }

    if (
      opts?.replace !== true &&
      (skillConflicts.length > 0 || commandConflicts.length > 0 || unstamped.length > 0 || ruleConflicts.length > 0)
    ) {
      return importConflict(
        skillConflicts,
        commandConflicts,
        unstamped.map((conflict) => conflict.name),
        ruleConflicts
      );
    }

    const succeeded: string[] = [];
    const failures: string[] = [];
    const written: string[] = [];

    for (const skill of sourceSkills) {
      const destFolder = `${skillRoot}/${skill.id}`;
      const destHash = hashSkillAt(this.fs, destFolder);
      if (destHash === skill.hash) {
        continue;
      }
      const copied = this.fs.copyDir(skill.folder, destFolder);
      if (!isOk(copied)) {
        failures.push(`'${skill.id}': ${copied.error.message}`);
        continue;
      }
      succeeded.push(destFolder);
      written.push(`${destFolder}/SKILL.md`);
    }

    for (const command of sourceCommands) {
      const destPath = commandFilePath(ide, command.name);
      if (!destPath) {
        continue;
      }
      const writtenFile = this.fs.writeFile(
        destPath,
        writeCommandFile(command.name, command.skills, command.contents)
      );
      if (!isOk(writtenFile)) {
        failures.push(`'/${command.name}': ${writtenFile.error.message}`);
        continue;
      }
      succeeded.push(destPath);
      written.push(destPath);
    }

    for (const rule of sourceRules) {
      const src = this.fs.readFile(underRoot(root, rule.path));
      if (!isOk(src)) {
        failures.push(`'${rule.name}': ${src.error.message}`);
        continue;
      }
      const destHash = hashFileAt(this.fs, rule.path);
      const srcHash = createHash('sha256').update(src.value, 'utf8').digest('hex');
      if (destHash === srcHash) {
        continue;
      }
      const writtenFile = this.fs.writeFile(rule.path, src.value);
      if (!isOk(writtenFile)) {
        failures.push(`'${rule.name}': ${writtenFile.error.message}`);
        continue;
      }
      succeeded.push(rule.path);
      written.push(rule.path);
    }

    const scanResult = this.scan();
    if (!isOk(scanResult)) {
      return scanResult;
    }

    for (const command of sourceCommands) {
      const existing = this.state.commands.find((record) => record.name === command.name);
      if (!existing) {
        this.state.commands.push({
          name: command.name,
          skills: [...command.skills],
          createdAt: new Date().toISOString(),
        });
      } else if (opts?.replace === true) {
        existing.skills = [...command.skills];
      }
    }

    const persistResult = this.persist();
    if (!isOk(persistResult)) {
      return err(new Error(`Failed to save import: ${persistResult.error.message}`));
    }

    this.writtenPaths = [...written, ...this.writtenPaths];
    return ok({ succeeded, failures });
  }

  scan(): Result<ScanResult> {
    const found = new Map<string, { hash: string; paths: string[] }>();

    for (const root of SCAN_SKILL_ROOTS) {
      const folders = this.fs.findSkillFolders(root);
      if (!isOk(folders)) {
        return err(folders.error);
      }

      for (const folder of folders.value) {
        const id = catalogId(folder, root);
        if (id === '') {
          continue;
        }

        const contents = this.fs.readFile(`${folder}/SKILL.md`);
        if (!isOk(contents)) {
          return err(contents.error);
        }

        const hash = createHash('sha256').update(contents.value, 'utf8').digest('hex');
        const existing = found.get(id);
        if (existing) {
          existing.paths.push(folder);
        } else {
          found.set(id, { hash, paths: [folder] });
        }
      }
    }

    const snapshot = {
      skills: this.state.skills.map((record) => ({ ...record, paths: [...record.paths], deployedTo: [...record.deployedTo] })),
      inbox: [...this.state.inbox],
      commands: this.state.commands.map(cloneCommandRecord),
    };

    const previous = new Map(this.state.skills.map((record) => [record.id, record]));
    const added: string[] = [];
    const changed: string[] = [];
    const nextSkills: SkillRecord[] = [];
    const matchedPrevious = new Set<string>();
    const matchedFound = new Set<string>();

    for (const [id, seen] of found) {
      const prev = previous.get(id);
      if (prev) {
        matchedPrevious.add(id);
        matchedFound.add(id);
        if (prev.hash !== seen.hash) {
          changed.push(id);
        }
        nextSkills.push({
          ...prev,
          hash: seen.hash,
          paths: seen.paths,
          ...(prev.source === 'skills.sh' && !prev.originHash ? { originHash: seen.hash } : {}),
        });
      }
    }

    const unmatchedPrev = this.state.skills.filter((record) => !matchedPrevious.has(record.id));
    const unmatchedFound = [...found.entries()].filter(([id]) => !matchedFound.has(id));
    const renameMap = new Map<string, string>();

    for (const prev of unmatchedPrev) {
      const renameIndex = unmatchedFound.findIndex(([, seen]) => seen.hash === prev.hash);
      if (renameIndex === -1) {
        continue;
      }
      const renamed = unmatchedFound.splice(renameIndex, 1)[0];
      if (!renamed) {
        continue;
      }
      const [newId, seen] = renamed;
      matchedPrevious.add(prev.id);
      renameMap.set(prev.id, newId);
      this.renameSkillId(prev.id, newId);
      nextSkills.push({
        ...prev,
        id: newId,
        hash: seen.hash,
        paths: seen.paths,
      });
    }

    const filed = new Set(this.state.commands.flatMap((command) => command.skills));

    for (const [id, seen] of unmatchedFound) {
      const origin = nextSkills.find(
        (record) => record.source === 'skills.sh' && record.id !== id && skillFolderName(record.id) === id
      );
      if (origin) {
        for (const path of seen.paths) {
          if (!origin.paths.includes(path)) origin.paths.push(path);
        }
        continue;
      }
      added.push(id);
      nextSkills.push({
        id,
        hash: seen.hash,
        paths: seen.paths,
        deployedTo: [],
        source: 'local',
      });
      if (!filed.has(id) && !this.state.inbox.includes(id)) {
        this.state.inbox.push(id);
      }
    }

    const gone: string[] = [];
    for (const prev of this.state.skills) {
      if (matchedPrevious.has(prev.id) || nextSkills.some((record) => record.id === prev.id)) {
        continue;
      }
      gone.push(prev.id);
      this.dropSkillId(prev.id);
    }

    this.state.skills = nextSkills;

    const commandPulls = this.pullStampedCommands(gone, renameMap);

    const persistResult = this.persist();
    if (!isOk(persistResult)) {
      this.state.skills = snapshot.skills;
      this.state.inbox = snapshot.inbox;
      this.state.commands = snapshot.commands;
      return err(new Error(`Failed to save scan: ${persistResult.error.message}`));
    }

    this.writeThroughAfterScan(gone);
    return ok({ added, gone, changed, commandPulls });
  }

  skills(): SkillRecord[] {
    return [...this.state.skills];
  }

  rules(): RuleRecord[] {
    const listed = collectRules(this.fs);
    return isOk(listed) ? collapseRules(listed.value) : [];
  }

  readRule(id: string): Result<string> {
    const listed = collectRules(this.fs);
    if (!isOk(listed)) {
      return err(new Error(`Rule '${id}' not found.`));
    }
    const target = listed.value.find((rule) => rule.id === id);
    if (!target) {
      return err(new Error(`Rule '${id}' not found.`));
    }
    const contents = this.fs.readFile(target.path);
    if (!isOk(contents)) {
      return err(new Error(`Rule '${id}' not found.`));
    }
    if (!id.includes('#')) {
      return contents;
    }
    const section = readRuleSection(contents.value, id.slice(id.indexOf('#') + 1));
    if (section === null) {
      return err(new Error(`Rule '${id}' not found.`));
    }
    return ok(section);
  }

  setAlwaysApply(id: string, alwaysApply: boolean): Result<RuleRecord> {
    if (!canToggleAlwaysApply(id)) {
      return err(new Error(`Cannot toggle always-apply on '${id}'.`));
    }
    const listed = collectRules(this.fs);
    if (!isOk(listed)) {
      return listed;
    }
    const target = listed.value.find((rule) => rule.id === id);
    if (!target) {
      return err(new Error(`Rule '${id}' not found.`));
    }

    const written: string[] = [];
    for (const copy of listed.value.filter((rule) => rule.name === target.name)) {
      if (!canToggleAlwaysApply(copy.id)) {
        continue;
      }
      const updated = this.writeAlwaysApplyCopy(copy, alwaysApply);
      if (!isOk(updated)) {
        return updated;
      }
      written.push(copy.path);
    }
    if (written.length === 0) {
      return err(new Error(`Rule '${id}' not found.`));
    }

    this.writtenPaths = [...written, ...this.writtenPaths];
    const nextListed = collectRules(this.fs);
    if (!isOk(nextListed)) {
      return nextListed;
    }
    const record = collapseRules(nextListed.value).find((rule) => rule.name === target.name);
    if (!record) {
      return err(new Error(`Rule '${id}' not found.`));
    }
    return ok(record);
  }

  async exportRules(
    targetIDE: IDE,
    opts?: { replace?: boolean; dest?: string }
  ): Promise<Result<ExportResult>> {
    const listed = collectRules(this.fs);
    if (!isOk(listed)) {
      return listed;
    }
    const sources = collapseRules(listed.value);
    if (sources.length === 0) {
      return err(new Error('No rules to export'));
    }

    type Planned = {
      name: string;
      dest: string;
      mode: 'file' | 'section';
      contents: string;
    };
    const planned: Planned[] = [];
    const failures: string[] = [];
    for (const rule of sources) {
      const targets = destRuleTargets(rule, targetIDE);
      if (targets.length === 0) {
        continue;
      }
      const contents = this.fs.readFile(rule.path);
      if (!isOk(contents)) {
        failures.push(`'${rule.name}': ${contents.error.message}`);
        continue;
      }
      const body = rule.id.includes('#')
        ? (readRuleSection(contents.value, rule.name) ?? contents.value)
        : contents.value;
      const stamped = stampRule(body, rule.name, rule.alwaysApply);
      for (const target of targets) {
        const dest = underRoot(opts?.dest, target.path);
        if (target.mode === 'file' && normalizeFsPath(dest) === normalizeFsPath(rule.path)) {
          continue;
        }
        planned.push({ name: rule.name, dest, mode: target.mode, contents: stamped });
      }
    }

    if (planned.length === 0) {
      const hadDest = sources.some((rule) => destRuleTargets(rule, targetIDE).length > 0);
      if (!hadDest) {
        return err(new Error(`No rule dest for ${targetIDE}`));
      }
    }

    if (opts?.replace !== true) {
      const conflicts: string[] = [];
      for (const item of planned) {
        if (this.ruleDestConflicts(item)) {
          conflicts.push(item.name);
        }
      }
      if (conflicts.length > 0) {
        return err(
          new Error(`Rule files exist (${conflicts.join(', ')}). Re-export with replace to overwrite.`),
          { code: 'RULE_EXPORT_CONFLICT', labels: conflicts }
        );
      }
    }

    const succeeded: string[] = [];
    const written: string[] = [];
    const writeOrder = [
      ...planned.filter((item) => item.mode === 'file'),
      ...planned.filter((item) => item.mode === 'section'),
    ];
    for (const item of writeOrder) {
      if (item.mode === 'file') {
        const destHash = hashFileAt(this.fs, item.dest);
        const srcHash = createHash('sha256').update(item.contents, 'utf8').digest('hex');
        if (destHash === srcHash) {
          if (!succeeded.includes(item.dest)) {
            succeeded.push(item.dest);
          }
          continue;
        }
        const writtenFile = this.fs.writeFile(item.dest, item.contents);
        if (!isOk(writtenFile)) {
          failures.push(`'${item.name}': ${writtenFile.error.message}`);
          continue;
        }
        succeeded.push(item.dest);
        written.push(item.dest);
        continue;
      }

      const existing = this.fs.readFile(item.dest);
      const current = isOk(existing) ? existing.value : '';
      const section = readRuleSection(current, item.name);
      if (section !== null && ruleBodiesEqual(section, item.contents)) {
        if (!succeeded.includes(item.dest)) {
          succeeded.push(item.dest);
        }
        continue;
      }
      const next = upsertRuleSection(current, item.name, item.contents);
      const writtenFile = this.fs.writeFile(item.dest, next);
      if (!isOk(writtenFile)) {
        failures.push(`'${item.name}': ${writtenFile.error.message}`);
        continue;
      }
      if (!succeeded.includes(item.dest)) {
        succeeded.push(item.dest);
      }
      written.push(item.dest);
    }

    this.writtenPaths = [...written, ...this.writtenPaths];
    return ok({ succeeded, failures });
  }

  async originChecks(): Promise<Result<OriginCheck[]>> {
    const checks: OriginCheck[] = [];
    for (const record of this.state.skills) {
      if (record.source !== 'skills.sh' || !record.originHash) {
        continue;
      }
      if (record.hash !== record.originHash) {
        checks.push({ skillId: record.id, status: 'edited' });
        continue;
      }
      const market = await this.skillsAdapter.skillHash(record.id);
      if (!isOk(market) || !market.value || market.value === record.originHash) {
        checks.push({ skillId: record.id, status: 'current' });
        continue;
      }
      checks.push({ skillId: record.id, status: 'update' });
    }
    return ok(checks);
  }

  async updateFromMarket(
    skillId: string,
    opts?: { replaceEdited?: boolean; dest?: string }
  ): Promise<Result<SkillRecord>> {
    const record = this.state.skills.find((skill) => skill.id === skillId);
    if (!record || record.source !== 'skills.sh' || !record.originHash) {
      return err(new Error(`Skill '${skillId}' has no market origin to update from.`));
    }
    if (record.hash !== record.originHash && !opts?.replaceEdited) {
      return err(new Error(`Skill '${skillId}' was edited. Reset from the preview if you want the market copy.`));
    }

    const keepInInbox = this.state.inbox.includes(skillId);
    const installed = await this.install(skillId, {
      dest: opts?.dest,
      replace: true,
      refreshOrigin: true,
    });
    if (!isOk(installed)) {
      return installed;
    }
    if (keepInInbox && !this.state.inbox.includes(skillId)) {
      this.state.inbox.push(skillId);
      const persistResult = this.persist();
      if (!isOk(persistResult)) {
        return err(new Error(`Failed to save inbox: ${persistResult.error.message}`));
      }
    }
    return ok(installed.value);
  }

  private dropSkillId(id: string): void {
    this.state.inbox = this.state.inbox.filter((entry) => entry !== id);
    for (const command of this.state.commands) {
      command.skills = command.skills.filter((skillId) => skillId !== id);
    }
  }

  private commandsFiling(skillId: string): Array<{ name: string }> {
    return this.state.commands
      .filter((command) => command.skills.includes(skillId))
      .map((command) => ({ name: command.name }));
  }

  /**
   * Deletes this skill’s files under `folder`, leaves nested skill
   * folders, then prunes empty parents up to the IDE skills root.
   */
  private removeSkillFolder(folder: string): Result<string[]> {
    const nested = this.fs.findSkillFolders(folder);
    if (!isOk(nested)) {
      return nested;
    }
    const keep = nested.value.filter((path) => path !== folder);

    const files = this.fs.listAllFiles(folder);
    if (!isOk(files)) {
      return files;
    }

    const muted: string[] = [];
    for (const file of files.value) {
      if (keep.some((skillDir) => file === `${skillDir}/SKILL.md` || file.startsWith(`${skillDir}/`))) {
        continue;
      }
      const removed = this.fs.removeFile(file);
      if (!isOk(removed)) {
        return removed;
      }
      muted.push(file);
    }

    const root = skillRootOf(folder);
    const candidates = new Set<string>(muted.map(parentDir).filter((dir) => dir !== ''));
    let dir: string | undefined = folder;
    while (dir && root && dir !== root) {
      candidates.add(dir);
      dir = parentDir(dir);
    }

    const deepestFirst = [...candidates].sort((a, b) => b.length - a.length);
    for (const emptyDir of deepestFirst) {
      if (!root || emptyDir === root || !emptyDir.startsWith(`${root}/`)) {
        continue;
      }
      const remaining = this.fs.listAllFiles(emptyDir);
      if (!isOk(remaining) || remaining.value.length > 0) {
        continue;
      }
      const removed = this.fs.removeDir(emptyDir);
      if (!isOk(removed)) {
        return removed;
      }
      muted.push(emptyDir);
    }

    return ok(muted);
  }

  private renameSkillId(fromId: string, toId: string): void {
    this.state.inbox = this.state.inbox.map((entry) => (entry === fromId ? toId : entry));
    for (const command of this.state.commands) {
      command.skills = command.skills.map((skillId) => (skillId === fromId ? toId : skillId));
    }
  }

  /**
   * Warn when a stamp's `skills:` disagrees with the map. Do not adopt
   * stamp ids into the map. Rename-map is applied so a renamed catalog
   * id does not look like a mismatch.
   */
  private pullStampedCommands(_gone: string[], renameMap: Map<string, string>): Array<{ ide: IDE; name: string }> {
    const pulls: Array<{ ide: IDE; name: string }> = [];

    for (const ide of ALL_IDES) {
      const dir = commandDir(ide);
      if (!dir) {
        continue;
      }
      const listed = this.fs.listFiles(dir);
      if (!isOk(listed)) {
        continue;
      }

      const ext = commandExtension(ide);
      for (const path of listed.value) {
        if (!path.endsWith(ext)) {
          continue;
        }
        const name = path.slice(path.lastIndexOf('/') + 1, -ext.length);
        if (name === '') {
          continue;
        }
        const contents = this.fs.readFile(path);
        if (!isOk(contents) || !isSkilStamped(contents.value)) {
          continue;
        }
        const parsed = parseStampedSkills(contents.value);
        if (parsed === null) {
          continue;
        }
        const remapped = parsed.map((id) => renameMap.get(id) ?? id);
        const record = this.state.commands.find((command) => command.name === name);
        const current = record?.skills ?? [];
        if (listsEqual(current, remapped)) {
          continue;
        }
        pulls.push({ ide, name });
      }
    }

    return pulls;
  }

  /**
   * Rewrite existing stamps for `names` on every dock. Refreshes
   * frontmatter and `## Skills`; keeps Goal/Sequence/Rules. Skips
   * missing files (no new stamp until export) and unstamped files.
   * Removes our stamp when the command is gone from the map.
   */
  writeThroughExisting(names: string[], dest?: string): string[] {
    const written: string[] = [];
    for (const ide of ALL_IDES) {
      const dir = commandDir(ide);
      if (!dir) {
        continue;
      }
      for (const name of names) {
        const path = commandFilePath(ide, name, dest);
        if (!path) {
          continue;
        }
        const existing = this.fs.readFile(path);
        if (!isOk(existing)) {
          continue;
        }
        if (!isSkilStamped(existing.value)) {
          continue;
        }

        const record = this.state.commands.find((command) => command.name === name);
        if (!record) {
          const removed = this.fs.removeFile(path);
          if (isOk(removed)) {
            written.push(path);
          }
          continue;
        }

        const result = this.fs.writeFile(path, writeCommandFile(name, record.skills, existing.value));
        if (isOk(result)) {
          written.push(path);
        }
      }
    }
    this.writtenPaths = written;
    return written;
  }

  /**
   * After scan: rewrite existing stamps when gone-id cleanup changed the
   * map. Skip when the stamp already matches, or when it disagrees with
   * extra ids that are still in the catalog (warn-only; user exports to
   * refresh).
   */
  writeThroughAfterScan(gone: string[] = []): void {
    const written: string[] = [];
    const goneSet = new Set(gone);

    for (const ide of ALL_IDES) {
      const dir = commandDir(ide);
      if (!dir) {
        continue;
      }
      const listed = this.fs.listFiles(dir);
      if (!isOk(listed)) {
        continue;
      }

      const ext = commandExtension(ide);
      for (const path of listed.value) {
        if (!path.endsWith(ext)) {
          continue;
        }
        const contents = this.fs.readFile(path);
        if (!isOk(contents) || !isSkilStamped(contents.value)) {
          continue;
        }
        const name = path.slice(path.lastIndexOf('/') + 1, -ext.length);
        const record = this.state.commands.find((command) => command.name === name);
        if (!record) {
          continue;
        }
        const stampSkills = parseStampedSkills(contents.value) ?? [];
        const current = record.skills;
        if (listsEqual(current, stampSkills) && isClosedSkilStamp(contents.value)) {
          continue;
        }
        const extras = stampSkills.filter((id) => !current.includes(id));
        const extrasAreGone = extras.length > 0 && extras.every((id) => goneSet.has(id));
        const missingOnStamp = current.some((id) => !stampSkills.includes(id));
        if (!extrasAreGone && !missingOnStamp && extras.length > 0) {
          continue;
        }
        written.push(...this.writeThroughExisting([name]));
      }
    }
    this.writtenPaths = written;
  }

  /**
   * `npx skills add --agent universal` lands in `.agents/skills/<short-name>`.
   * Move that folder under the full market id so scan does not treat the id
   * as gone and strip it from the command.
   */
  private relocateNpxInstall(skillId: string, dest?: string, replace?: boolean): Result<void> {
    const deployPath = underRoot(dest, `${SKILL_ROOT_BY_IDE.agents}/${skillId}`);
    const destExists = isOk(this.fs.readFile(`${deployPath}/SKILL.md`));
    if (destExists && !replace) {
      return ok(undefined);
    }

    const npxFolder = underRoot(dest, `${SKILL_ROOT_BY_IDE.agents}/${skillFolderName(skillId)}`);
    const npxExists = npxFolder !== deployPath && isOk(this.fs.readFile(`${npxFolder}/SKILL.md`));
    if (!npxExists) {
      if (replace) {
        return err(new Error(`Failed to replace skill '${skillId}': market copy was not downloaded.`));
      }
      return ok(undefined);
    }

    if (destExists && replace) {
      const cleared = this.fs.removeDir(deployPath);
      if (!isOk(cleared)) {
        return err(
          new Error(`Failed to replace skill '${skillId}' at ${deployPath}: ${cleared.error.message}`)
        );
      }
    }

    const copied = this.fs.copyDir(npxFolder, deployPath);
    if (!isOk(copied)) {
      return err(new Error(`Failed to place skill '${skillId}' in ${deployPath}: ${copied.error.message}`));
    }
    const removed = this.fs.removeDir(npxFolder);
    if (!isOk(removed)) {
      return err(new Error(`Failed to remove stray skill folder '${npxFolder}': ${removed.error.message}`));
    }
    return ok(undefined);
  }

  /**
   * Second half of a market install: mirror the fresh `.agents` copy into
   * the other live tree. Skips when there is nothing on disk to mirror
   * (an adapter that failed to deliver is surfaced by the empty hash, not
   * a copy error) or when the mirror already exists and this is not a
   * replace.
   */
  private mirrorLiveInstall(skillId: string, from: string, to: string, replace: boolean): Result<void> {
    if (!isOk(this.fs.readFile(`${from}/SKILL.md`))) {
      return ok(undefined);
    }
    const destExists = isOk(this.fs.readFile(`${to}/SKILL.md`));
    if (destExists) {
      if (!replace) {
        return ok(undefined);
      }
      const cleared = this.fs.removeDir(to);
      if (!isOk(cleared)) {
        return err(new Error(`Failed to replace skill '${skillId}' at ${to}: ${cleared.error.message}`));
      }
    }
    const copied = this.fs.copyDir(from, to);
    if (!isOk(copied)) {
      return err(new Error(`Failed to place skill '${skillId}' in ${to}: ${copied.error.message}`));
    }
    return ok(undefined);
  }

  private recordLocalDeploy(skillId: string, targetIDE: IDE, dest: string): void {
    const existingIndex = this.state.skills.findIndex((skill) => skill.id === skillId);
    const previous = existingIndex >= 0 ? this.state.skills[existingIndex] : undefined;
    if (!previous || existingIndex < 0) {
      return;
    }

    this.state.skills[existingIndex] = {
      ...previous,
      hash: hashSkillAt(this.fs, dest) ?? previous.hash,
      paths: previous.paths.includes(dest) ? previous.paths : [...previous.paths, dest],
      deployedTo: upsertDeploy(previous.deployedTo, {
        ide: targetIDE,
        path: dest,
        installedAt: new Date().toISOString(),
      }),
    };
  }

  private unstampedConflicts(
    names: string[],
    ide: IDE,
    dest?: string
  ): Array<{ name: string; path: string }> {
    const conflicts: Array<{ name: string; path: string }> = [];
    for (const name of names) {
      const path = commandFilePath(ide, name, dest);
      if (!path) {
        continue;
      }
      const existing = this.fs.readFile(path);
      if (isOk(existing) && !isSkilStamped(existing.value)) {
        conflicts.push({ name, path });
      }
    }
    return conflicts;
  }

  private writeAlwaysApplyCopy(copy: RuleRecord, alwaysApply: boolean): Result<void> {
    const contents = this.fs.readFile(copy.path);
    if (!isOk(contents)) {
      return err(new Error(`Rule '${copy.id}' not found.`));
    }
    if (copy.id.includes('#')) {
      const section = readRuleSection(contents.value, copy.name);
      if (section === null) {
        return err(new Error(`Rule '${copy.id}' not found.`));
      }
      const next = upsertRuleSection(contents.value, copy.name, withAlwaysApply(section, alwaysApply));
      const written = this.fs.writeFile(copy.path, next);
      if (!isOk(written)) {
        return err(new Error(`Failed to update rule '${copy.id}': ${written.error.message}`));
      }
      return ok(undefined);
    }
    const written = this.fs.writeFile(copy.path, withAlwaysApply(contents.value, alwaysApply));
    if (!isOk(written)) {
      return err(new Error(`Failed to update rule '${copy.id}': ${written.error.message}`));
    }
    return ok(undefined);
  }

  private ruleDestConflicts(item: { name: string; dest: string; mode: 'file' | 'section'; contents: string }): boolean {
    if (item.mode === 'file') {
      const destHash = hashFileAt(this.fs, item.dest);
      const srcHash = createHash('sha256').update(item.contents, 'utf8').digest('hex');
      return destHash !== undefined && destHash !== srcHash;
    }
    const existing = this.fs.readFile(item.dest);
    if (!isOk(existing)) {
      return false;
    }
    const section = readRuleSection(existing.value, item.name);
    return section !== null && !ruleBodiesEqual(section, item.contents);
  }

  /** Writes state to disk. Returns an error Result if the write fails; callers must check it rather than assume the mutation was saved. */
  private persist(): Result<void> {
    this.state.version = STATE_VERSION;
    return this.fs.writeJSON(STATE_PATH, this.state);
  }

  /**
   * Picks up skills already installed by external tooling (e.g. a bare
   * `npx skills add` run outside skil) so state stays in sync.
   * In-memory only: persisted on the next mutation, not on construction.
   */
  private mergeExternallyInstalledSkills(): void {
    const known = new Set(this.state.installedSkills.map((s) => s.id));
    for (const skill of this.skillsAdapter.getInstalled()) {
      if (!known.has(skill.id)) {
        this.state.installedSkills.push(skill);
        known.add(skill.id);
      }
    }
  }
}

function listsEqual(a: string[], b: string[]): boolean {
  return a.length === b.length && a.every((id, index) => id === b[index]);
}

function catalogId(folder: string, root: string): string {
  if (folder === root) {
    return '.';
  }
  const prefix = `${root}/`;
  return folder.startsWith(prefix) ? folder.slice(prefix.length) : folder;
}

function skillRootOf(path: string): (typeof SKILL_ROOTS)[number] | undefined {
  return SKILL_ROOTS.find((root) => path === root || path.startsWith(`${root}/`));
}

function parentDir(path: string): string {
  const normalized = path.replace(/\\/g, '/').replace(/\/+$/, '');
  const index = normalized.lastIndexOf('/');
  return index <= 0 ? '' : normalized.slice(0, index);
}

function cloneSkillRecord(record: SkillRecord | undefined): SkillRecord | undefined {
  if (!record) {
    return undefined;
  }
  return {
    ...record,
    paths: [...record.paths],
    deployedTo: record.deployedTo.map((entry) => ({ ...entry })),
  };
}

function hashFileAt(fs: IFileSystemAdapter, path: string): string | undefined {
  const contents = fs.readFile(path);
  if (!isOk(contents)) {
    return undefined;
  }
  return createHash('sha256').update(contents.value, 'utf8').digest('hex');
}

function hashSkillAt(fs: IFileSystemAdapter, folder: string): string | undefined {
  const contents = fs.readFile(`${folder}/SKILL.md`);
  if (!isOk(contents)) {
    return undefined;
  }
  return createHash('sha256').update(contents.value, 'utf8').digest('hex');
}

function upsertDeploy(
  existing: SkillRecord['deployedTo'],
  entry: SkillRecord['deployedTo'][number]
): SkillRecord['deployedTo'] {
  const index = existing.findIndex((deploy) => deploy.ide === entry.ide);
  if (index === -1) {
    return [...existing, entry];
  }
  return existing.map((deploy, i) => (i === index ? entry : deploy));
}
