import { createHash } from 'node:crypto';
import type { ICollectionEngine } from '../interfaces/engine.js';
import type { IFileSystemAdapter, IConfigAdapter, ISkillsAdapter } from '../interfaces/adapters.js';
import type {
  BrowseView,
  Collection,
  Command,
  CommandRecord,
  ExportResult,
  IDE,
  ScanResult,
  Skill,
  SkillRecord,
  State,
  SyncResult,
} from '../types/index.js';
import { err, isOk, ok, type Result } from './result.js';
import { isSkilStamped, parseStampedSkills, writeCommandFile } from './command-file.js';

/** Path to the persisted engine state, relative to the project root. */
export const STATE_PATH = '.skil/state.json';

const LEFTOVER_STATE_PATH = '.contextkit/state.json';

/** Current state schema version. See `State`'s doc comment for the v4 → v5 notes. */
const STATE_VERSION = '5.0';

const DEFAULT_IDE: IDE = 'cursor';

const ALL_IDES: IDE[] = ['cursor', 'claude', 'windsurf', 'agents'];

/** Command name reserved for the Inbox holding list on `State`. */
const INBOX_NAME = 'inbox';

/** Store `/build` as `build`. UI may still display the slash. */
function normalizeCommandName(name: string): string {
  return name.startsWith('/') ? name.slice(1) : name;
}

function commandNotFound(name: string): Error {
  return new Error(`Command '${name}' not found. Run 'skil list' to see available commands.`);
}

/** Skill trees we pull from. We never walk `commands/`. */
const SKILL_ROOTS = ['.cursor/skills', '.claude/skills', '.windsurf/skills', '.agents/skills'] as const;

const SKILL_ROOT_BY_IDE: Record<IDE, string> = {
  cursor: '.cursor/skills',
  claude: '.claude/skills',
  windsurf: '.windsurf/skills',
  agents: '.agents/skills',
};

/** Where we write our command file. Windsurf uses workflows, not commands/. */
const COMMAND_DIR_BY_IDE: Record<IDE, string> = {
  cursor: '.cursor/commands',
  claude: '.claude/commands',
  windsurf: '.windsurf/workflows',
  agents: '.agents/commands',
};

/** Prefix a workspace-relative path with an optional dest root. */
function underRoot(root: string | undefined, relative: string): string {
  if (!root) return relative;
  return `${root.replace(/\\/g, '/').replace(/\/+$/, '')}/${relative}`;
}

function commandFilePath(ide: IDE, name: string, dest?: string): string {
  return underRoot(dest, `${COMMAND_DIR_BY_IDE[ide]}/${name}.md`);
}

function unstampedConflictError(conflicts: Array<{ name: string; path: string }>): Error {
  const names = conflicts.map((conflict) => `/${conflict.name}`).join(', ');
  return new Error(
    `Command files exist and were not generated by skil (${names}). Re-export with replace to overwrite.`
  );
}

/** On-disk command that may still use v4 `skills[]`. */
interface PersistedCommand {
  name: string;
  skills?: string[];
  membership?: Partial<Record<IDE, string[]>>;
  createdAt: string;
  command?: string;
}

/** On-disk shape that may still use v3 `collections`. */
interface PersistedState {
  version?: string;
  commands?: PersistedCommand[];
  collections?: PersistedCommand[];
  skills?: SkillRecord[];
  inbox?: string[];
  installedSkills?: Skill[];
}

function emptyState(): State {
  return { commands: [], skills: [], installedSkills: [], inbox: [], version: STATE_VERSION };
}

function toCommandRecord(raw: PersistedCommand): CommandRecord {
  const membership =
    raw.membership !== undefined
      ? cloneMembership(raw.membership)
      : { [DEFAULT_IDE]: [...(raw.skills ?? [])] };
  return {
    name: raw.name,
    membership,
    createdAt: raw.createdAt,
    ...(raw.command !== undefined ? { command: raw.command } : {}),
  };
}

function normalizeState(raw: PersistedState): State {
  const commands = (raw.commands ?? raw.collections ?? []).map(toCommandRecord);
  return {
    commands,
    skills: raw.skills ?? [],
    installedSkills: raw.installedSkills ?? [],
    inbox: raw.inbox ?? [],
    version: raw.version ?? STATE_VERSION,
  };
}

function toView(record: CommandRecord, ide: IDE): Command {
  return {
    name: record.name,
    skills: [...(record.membership[ide] ?? [])],
    createdAt: record.createdAt,
    ...(record.command !== undefined ? { command: record.command } : {}),
  };
}

function cloneMembership(membership: Partial<Record<IDE, string[]>>): Partial<Record<IDE, string[]>> {
  const next: Partial<Record<IDE, string[]>> = {};
  for (const ide of ALL_IDES) {
    const list = membership[ide];
    if (list !== undefined) {
      next[ide] = [...list];
    }
  }
  return next;
}

function cloneCommandRecord(record: CommandRecord): CommandRecord {
  return {
    ...record,
    membership: cloneMembership(record.membership),
  };
}

function hasMembership(record: CommandRecord, ide: IDE): boolean {
  return record.membership[ide] !== undefined;
}

function commandNotOnIde(name: string, ide: IDE): Error {
  return new Error(`Command '${name}' not found on ${ide}. Run 'skil list --ide ${ide}' to see available commands.`);
}

/** Load `.skil/state.json`. Missing file → empty state. Leftover `.contextkit/state.json` with no `.skil/` file is an error. */
function loadState(fs: IFileSystemAdapter): State {
  const current = fs.readJSON<PersistedState>(STATE_PATH);
  if (isOk(current)) {
    return normalizeState(current.value);
  }
  const leftover = fs.readJSON<PersistedState>(LEFTOVER_STATE_PATH);
  if (isOk(leftover)) {
    throw new Error(
      'Found leftover .contextkit/state.json. Move it to .skil/state.json and retry.'
    );
  }
  return emptyState();
}

/**
 * CollectionEngine is skil's deep module: see ICollectionEngine for the
 * public contract. This class owns state management, validation, and
 * coordination with the injected adapters.
 */
export class CollectionEngine implements ICollectionEngine {
  private state: State;
  private writtenPaths: string[] = [];

  constructor(
    private readonly fs: IFileSystemAdapter,
    private readonly config: IConfigAdapter,
    private readonly skillsAdapter: ISkillsAdapter
  ) {
    this.state = loadState(this.fs);
    this.mergeExternallyInstalledSkills();
  }

  lastWrittenPaths(): string[] {
    return [...this.writtenPaths];
  }

  create(name: string, skillIds: string[], command?: string, ide: IDE = DEFAULT_IDE): Result<Collection> {
    name = normalizeCommandName(name);
    if (name === INBOX_NAME) {
      return err(new Error(`'inbox' is not a command. Inbox is a holding list of skill IDs — add with 'skil inbox add' and file them onto a named command.`));
    }

    const existing = this.state.commands.find((c) => c.name === name);
    if (existing) {
      if (hasMembership(existing, ide)) {
        return err(new Error(`Command '${name}' already exists. Choose a different name or run 'skil list' to see existing commands.`));
      }
      const snapshot = cloneCommandRecord(existing);
      existing.membership[ide] = [...skillIds];
      const persistResult = this.persist();
      if (!isOk(persistResult)) {
        existing.membership = snapshot.membership;
        return err(new Error(`Failed to save command '${name}': ${persistResult.error.message}`));
      }
      this.writeThrough(ide, [name]);
      return ok(toView(existing, ide));
    }

    const record: CommandRecord = {
      name,
      membership: { [ide]: [...skillIds] },
      createdAt: new Date().toISOString(),
      ...(command !== undefined ? { command } : {}),
    };
    this.state.commands.push(record);
    const persistResult = this.persist();
    if (!isOk(persistResult)) {
      this.state.commands.pop();
      return err(new Error(`Failed to save command '${name}': ${persistResult.error.message}`));
    }

    this.writeThrough(ide, [name]);
    return ok(toView(record, ide));
  }

  addSkill(name: string, skillId: string, ide: IDE = DEFAULT_IDE): Result<Collection> {
    name = normalizeCommandName(name);
    const record = this.state.commands.find((c) => c.name === name);
    if (!record || !hasMembership(record, ide)) {
      return err(record ? commandNotOnIde(name, ide) : commandNotFound(name));
    }
    const list = record.membership[ide] ?? [];
    if (list.includes(skillId)) {
      return ok(toView(record, ide));
    }

    const snapshot = [...list];
    list.push(skillId);
    record.membership[ide] = list;
    const persistResult = this.persist();
    if (!isOk(persistResult)) {
      record.membership[ide] = snapshot;
      return err(new Error(`Failed to save command '${name}': ${persistResult.error.message}`));
    }

    this.writeThrough(ide, [name]);
    return ok(toView(record, ide));
  }

  removeSkill(name: string, skillId: string, ide: IDE = DEFAULT_IDE): Result<Collection> {
    name = normalizeCommandName(name);
    const record = this.state.commands.find((c) => c.name === name);
    if (!record || !hasMembership(record, ide)) {
      return err(record ? commandNotOnIde(name, ide) : commandNotFound(name));
    }

    const list = record.membership[ide] ?? [];
    const index = list.indexOf(skillId);
    if (index === -1) {
      return ok(toView(record, ide));
    }

    const snapshot = [...list];
    list.splice(index, 1);
    record.membership[ide] = list;
    const persistResult = this.persist();
    if (!isOk(persistResult)) {
      record.membership[ide] = snapshot;
      return err(new Error(`Failed to save command '${name}': ${persistResult.error.message}`));
    }

    this.writeThrough(ide, [name]);
    return ok(toView(record, ide));
  }

  getCommand(name: string): Result<string> {
    const record = this.state.commands.find((c) => c.name === name);
    if (!record) {
      return err(new Error(`Collection '${name}' not found. Run 'skil list' to see available collections.`));
    }
    if (!record.command) {
      return err(new Error(`Collection '${name}' has no command defined. Create it with 'skil create ${name} --command "<cmd>"'.`));
    }
    return ok(record.command);
  }

  list(ide: IDE = DEFAULT_IDE): Collection[] {
    return this.state.commands.filter((c) => hasMembership(c, ide)).map((c) => toView(c, ide));
  }

  sync(configPath: string): Result<SyncResult> {
    const configResult = this.config.read(configPath);
    if (!isOk(configResult)) {
      return err(configResult.error);
    }

    const validation = this.config.validate(configResult.value);
    if (!isOk(validation)) {
      return err(validation.error);
    }

    const configNames = new Set(Object.keys(configResult.value.collections));
    const warnings = this.state.commands
      .filter((c) => !configNames.has(c.name))
      .map((c) => `Local collection '${c.name}' is not in the config file. Add it to '${configPath}' or remove it locally.`);

    const snapshot = this.state.commands.map(cloneCommandRecord);
    const synced: string[] = [];
    for (const [name, skillIds] of Object.entries(configResult.value.collections)) {
      const existing = this.state.commands.find((c) => c.name === name);
      if (existing) {
        existing.membership[DEFAULT_IDE] = skillIds;
      } else {
        this.state.commands.push({
          name,
          membership: { [DEFAULT_IDE]: skillIds },
          createdAt: new Date().toISOString(),
        });
      }
      synced.push(name);
    }

    const persistResult = this.persist();
    if (!isOk(persistResult)) {
      this.state.commands = snapshot;
      return err(new Error(`Failed to save synced collections: ${persistResult.error.message}`));
    }

    return ok({ synced, warnings });
  }

  async install(skillId: string, targetIDE: IDE, opts?: { dest?: string }): Promise<Result<SkillRecord>> {
    const result = await this.skillsAdapter.install(
      skillId,
      targetIDE,
      opts?.dest ? { cwd: opts.dest } : undefined
    );
    if (!isOk(result)) {
      return err(result.error);
    }

    const deployPath = underRoot(opts?.dest, `${SKILL_ROOT_BY_IDE[targetIDE]}/${skillId}`);
    const installedAt = new Date().toISOString();
    const existingIndex = this.state.skills.findIndex((s) => s.id === skillId);
    const previous = existingIndex >= 0 ? cloneSkillRecord(this.state.skills[existingIndex]) : undefined;
    const hash = hashSkillAt(this.fs, deployPath) ?? previous?.hash ?? '';

    const record: SkillRecord = previous
      ? {
          ...previous,
          hash,
          paths: previous.paths.includes(deployPath) ? previous.paths : [...previous.paths, deployPath],
          deployedTo: upsertDeploy(previous.deployedTo, { ide: targetIDE, path: deployPath, installedAt }),
        }
      : {
          id: skillId,
          hash,
          paths: [deployPath],
          deployedTo: [{ ide: targetIDE, path: deployPath, installedAt }],
          source: 'skills.sh',
        };

    if (existingIndex >= 0) {
      this.state.skills[existingIndex] = record;
    } else {
      this.state.skills.push(record);
    }

    const persistResult = this.persist();
    if (!isOk(persistResult)) {
      if (previous && existingIndex >= 0) {
        this.state.skills[existingIndex] = previous;
      } else {
        this.state.skills.pop();
      }
      return err(new Error(`Failed to save installed skill '${skillId}': ${persistResult.error.message}`));
    }

    return ok(record);
  }

  search(query: string): Promise<Result<Skill[]>> {
    return this.skillsAdapter.search(query);
  }

  browse(view: BrowseView): Promise<Result<Skill[]>> {
    return this.skillsAdapter.browse(view);
  }

  convert(skillId: string, targetIDE: IDE): Promise<Result<void>> {
    return this.skillsAdapter.convert(skillId, targetIDE);
  }

  async export(collectionNames: string[], targetIDE: IDE): Promise<Result<ExportResult>> {
    const succeeded: string[] = [];
    const failures: string[] = [];

    for (const name of collectionNames) {
      const record = this.state.commands.find((c) => c.name === name);
      if (!record) {
        failures.push(`Collection '${name}' not found. Run 'skil list' to see available collections.`);
        continue;
      }

      for (const skillId of record.membership[targetIDE] ?? record.membership[DEFAULT_IDE] ?? []) {
        const result = await this.skillsAdapter.convert(skillId, targetIDE);
        if (isOk(result)) {
          succeeded.push(`${name}:${skillId}`);
        } else {
          failures.push(`'${name}:${skillId}': ${result.error.message}`);
        }
      }
    }

    return ok({ succeeded, failures });
  }

  async exportCommand(
    name: string,
    targetIDE: IDE,
    opts?: { replace?: boolean; dest?: string }
  ): Promise<Result<ExportResult>> {
    name = normalizeCommandName(name);
    const command = this.state.commands.find((c) => c.name === name);
    if (!command || !hasMembership(command, targetIDE)) {
      return err(command ? commandNotOnIde(name, targetIDE) : commandNotFound(name));
    }

    const skills = command.membership[targetIDE] ?? [];
    const path = commandFilePath(targetIDE, name, opts?.dest);
    const existing = this.fs.readFile(path);
    if (isOk(existing) && !isSkilStamped(existing.value) && opts?.replace !== true) {
      return err(unstampedConflictError([{ name, path }]));
    }

    const written = this.fs.writeFile(
      path,
      writeCommandFile(name, skills, isOk(existing) ? existing.value : undefined, {
        reset: opts?.replace === true,
      })
    );
    if (!isOk(written)) {
      return err(new Error(`Failed to write command file '${path}': ${written.error.message}`));
    }
    this.writtenPaths = [path];

    const succeeded = [path];
    const failures: string[] = [];
    let copied = false;

    for (const skillId of skills) {
      const skillFolder = underRoot(opts?.dest, `${SKILL_ROOT_BY_IDE[targetIDE]}/${skillId}`);
      if (isOk(this.fs.readFile(`${skillFolder}/SKILL.md`))) {
        continue;
      }

      const record = this.state.skills.find((skill) => skill.id === skillId);
      const source = record?.paths.find(
        (folder) => folder !== skillFolder && isOk(this.fs.readFile(`${folder}/SKILL.md`))
      );
      if (source) {
        const copyResult = this.fs.copyDir(source, skillFolder);
        if (!isOk(copyResult)) {
          failures.push(`'${skillId}': ${copyResult.error.message}`);
          continue;
        }
        this.recordLocalDeploy(skillId, targetIDE, skillFolder);
        succeeded.push(skillFolder);
        copied = true;
        continue;
      }

      const installed = await this.install(skillId, targetIDE, opts?.dest ? { dest: opts.dest } : undefined);
      if (!isOk(installed)) {
        failures.push(`'${skillId}': ${installed.error.message}`);
        continue;
      }
      succeeded.push(skillFolder);
    }

    if (copied) {
      const persistResult = this.persist();
      if (!isOk(persistResult)) {
        failures.push(`Failed to save skill deploys: ${persistResult.error.message}`);
      }
    }

    return ok({ succeeded, failures });
  }

  async exportAll(
    targetIDE: IDE,
    opts?: { replace?: boolean; dest?: string }
  ): Promise<Result<ExportResult>> {
    const commands = this.state.commands.filter((command) => hasMembership(command, targetIDE));
    if (commands.length === 0) {
      return err(new Error('No commands to export'));
    }

    if (opts?.replace !== true) {
      const conflicts = this.unstampedConflicts(
        commands.map((command) => command.name),
        targetIDE,
        opts?.dest
      );
      if (conflicts.length > 0) {
        return err(unstampedConflictError(conflicts));
      }
    }

    const succeeded: string[] = [];
    const failures: string[] = [];
    for (const command of commands) {
      const result = await this.exportCommand(command.name, targetIDE, opts);
      if (!isOk(result)) {
        return result;
      }
      succeeded.push(...result.value.succeeded);
      failures.push(...result.value.failures);
    }
    return ok({ succeeded, failures });
  }

  inbox(): string[] {
    return [...this.state.inbox];
  }

  addToInbox(skillId: string): Result<string[]> {
    if (this.state.inbox.includes(skillId)) {
      return ok(this.inbox());
    }

    this.state.inbox.push(skillId);
    const persistResult = this.persist();
    if (!isOk(persistResult)) {
      this.state.inbox.pop();
      return err(new Error(`Failed to save inbox: ${persistResult.error.message}`));
    }

    return ok(this.inbox());
  }

  removeFromInbox(skillId: string): Result<string[]> {
    const index = this.state.inbox.indexOf(skillId);
    if (index === -1) {
      return ok(this.inbox());
    }

    this.state.inbox.splice(index, 1);
    const persistResult = this.persist();
    if (!isOk(persistResult)) {
      this.state.inbox.splice(index, 0, skillId);
      return err(new Error(`Failed to save inbox: ${persistResult.error.message}`));
    }

    return ok(this.inbox());
  }

  deleteSkill(skillId: string): Result<void> {
    const record = this.state.skills.find((skill) => skill.id === skillId);
    const filed = this.commandsFiling(skillId);
    if (!record && !this.state.inbox.includes(skillId) && filed.length === 0) {
      return ok(undefined);
    }

    const snapshot = {
      skills: this.state.skills.map((skill) => ({
        ...skill,
        paths: [...skill.paths],
        deployedTo: skill.deployedTo.map((entry) => ({ ...entry })),
      })),
      inbox: [...this.state.inbox],
      commands: this.state.commands.map(cloneCommandRecord),
    };

    if (record) {
      this.state.skills = this.state.skills.filter((skill) => skill.id !== skillId);
    }
    this.dropSkillId(skillId);

    const persistResult = this.persist();
    if (!isOk(persistResult)) {
      this.state.skills = snapshot.skills;
      this.state.inbox = snapshot.inbox;
      this.state.commands = snapshot.commands;
      return err(new Error(`Failed to save after deleting '${skillId}': ${persistResult.error.message}`));
    }

    const muted: string[] = [];
    if (record) {
      for (const folder of record.paths) {
        if (!skillRootOf(folder)) {
          continue;
        }
        const removed = this.removeSkillFolder(folder);
        if (!isOk(removed)) {
          return err(removed.error);
        }
        muted.push(...removed.value);
      }
    }

    const written: string[] = [];
    for (const ide of ALL_IDES) {
      const names = [...new Set(filed.filter((entry) => entry.ide === ide).map((entry) => entry.name))];
      if (names.length > 0) {
        written.push(...this.writeThrough(ide, names));
      }
    }
    this.writtenPaths = [...muted, ...written];
    return ok(undefined);
  }

  file(skillId: string, commandName: string, ide: IDE = DEFAULT_IDE): Result<Collection> {
    commandName = normalizeCommandName(commandName);
    const record = this.state.commands.find((c) => c.name === commandName);
    if (!record || !hasMembership(record, ide)) {
      return err(record ? commandNotOnIde(commandName, ide) : commandNotFound(commandName));
    }

    if (!this.state.inbox.includes(skillId)) {
      return err(new Error(`'${skillId}' is not in Inbox. Add it first, then file it onto a command.`));
    }

    const skillsSnapshot = [...(record.membership[ide] ?? [])];
    const list = record.membership[ide] ?? [];

    if (!list.includes(skillId)) {
      list.push(skillId);
    }
    record.membership[ide] = list;

    const persistResult = this.persist();
    if (!isOk(persistResult)) {
      record.membership[ide] = skillsSnapshot;
      return err(new Error(`Failed to save command '${commandName}': ${persistResult.error.message}`));
    }

    this.writeThrough(ide, [commandName]);
    return ok(toView(record, ide));
  }

  delete(name: string, ide: IDE = DEFAULT_IDE): Result<void> {
    name = normalizeCommandName(name);
    const index = this.state.commands.findIndex((c) => c.name === name);
    if (index === -1) {
      return err(commandNotFound(name));
    }

    const record = this.state.commands[index];
    if (record === undefined || !hasMembership(record, ide)) {
      return err(record ? commandNotOnIde(name, ide) : commandNotFound(name));
    }

    const snapshot = cloneCommandRecord(record);
    delete record.membership[ide];
    const dropRow = Object.keys(record.membership).length === 0;
    if (dropRow) {
      this.state.commands.splice(index, 1);
    }

    const persistResult = this.persist();
    if (!isOk(persistResult)) {
      if (dropRow) {
        this.state.commands.splice(index, 0, snapshot);
      } else {
        record.membership = snapshot.membership;
      }
      return err(new Error(`Failed to save after deleting '${name}': ${persistResult.error.message}`));
    }

    this.writeThrough(ide, [name]);
    return ok(undefined);
  }

  async copyTo(
    name: string,
    fromIde: IDE,
    toIde: IDE,
    opts?: { replace?: boolean; dest?: string }
  ): Promise<Result<ExportResult>> {
    name = normalizeCommandName(name);
    const record = this.state.commands.find((c) => c.name === name);
    if (!record || !hasMembership(record, fromIde)) {
      return err(record ? commandNotOnIde(name, fromIde) : commandNotFound(name));
    }

    const destPath = commandFilePath(toIde, name, opts?.dest);
    const existing = this.fs.readFile(destPath);
    if (isOk(existing) && !isSkilStamped(existing.value) && opts?.replace !== true) {
      return err(unstampedConflictError([{ name, path: destPath }]));
    }

    const snapshot = cloneCommandRecord(record);
    record.membership[toIde] = [...(record.membership[fromIde] ?? [])];
    const persistResult = this.persist();
    if (!isOk(persistResult)) {
      record.membership = snapshot.membership;
      return err(new Error(`Failed to save command '${name}': ${persistResult.error.message}`));
    }

    return this.exportCommand(name, toIde, opts);
  }

  async copyAll(
    fromIde: IDE,
    toIde: IDE,
    opts?: { replace?: boolean; dest?: string }
  ): Promise<Result<ExportResult>> {
    const names = this.list(fromIde).map((command) => command.name);
    if (names.length === 0) {
      return err(new Error(`No commands to copy from ${fromIde}`));
    }

    if (opts?.replace !== true) {
      const conflicts = this.unstampedConflicts(names, toIde, opts?.dest);
      if (conflicts.length > 0) {
        return err(unstampedConflictError(conflicts));
      }
    }

    const succeeded: string[] = [];
    const failures: string[] = [];
    for (const name of names) {
      const result = await this.copyTo(name, fromIde, toIde, opts);
      if (!isOk(result)) {
        return result;
      }
      succeeded.push(...result.value.succeeded);
      failures.push(...result.value.failures);
    }
    return ok({ succeeded, failures });
  }

  scan(): Result<ScanResult> {
    const found = new Map<string, { hash: string; paths: string[] }>();

    for (const root of SKILL_ROOTS) {
      const folders = this.fs.findSkillFolders(root);
      if (!isOk(folders)) {
        return err(folders.error);
      }

      for (const folder of folders.value) {
        const id = catalogId(folder, root);
        if (id === '') {
          continue;
        }

        const contents = this.fs.readFile(`${folder}/SKILL.md`);
        if (!isOk(contents)) {
          return err(contents.error);
        }

        const hash = createHash('sha256').update(contents.value, 'utf8').digest('hex');
        const existing = found.get(id);
        if (existing) {
          existing.paths.push(folder);
        } else {
          found.set(id, { hash, paths: [folder] });
        }
      }
    }

    const snapshot = {
      skills: this.state.skills.map((record) => ({ ...record, paths: [...record.paths], deployedTo: [...record.deployedTo] })),
      inbox: [...this.state.inbox],
      commands: this.state.commands.map(cloneCommandRecord),
    };

    const previous = new Map(this.state.skills.map((record) => [record.id, record]));
    const added: string[] = [];
    const changed: string[] = [];
    const nextSkills: SkillRecord[] = [];
    const matchedPrevious = new Set<string>();
    const matchedFound = new Set<string>();

    for (const [id, seen] of found) {
      const prev = previous.get(id);
      if (prev) {
        matchedPrevious.add(id);
        matchedFound.add(id);
        if (prev.hash !== seen.hash) {
          changed.push(id);
        }
        nextSkills.push({
          ...prev,
          hash: seen.hash,
          paths: seen.paths,
        });
      }
    }

    const unmatchedPrev = this.state.skills.filter((record) => !matchedPrevious.has(record.id));
    const unmatchedFound = [...found.entries()].filter(([id]) => !matchedFound.has(id));
    const renameMap = new Map<string, string>();

    for (const prev of unmatchedPrev) {
      const renameIndex = unmatchedFound.findIndex(([, seen]) => seen.hash === prev.hash);
      if (renameIndex === -1) {
        continue;
      }
      const renamed = unmatchedFound.splice(renameIndex, 1)[0];
      if (!renamed) {
        continue;
      }
      const [newId, seen] = renamed;
      matchedPrevious.add(prev.id);
      renameMap.set(prev.id, newId);
      this.renameSkillId(prev.id, newId);
      nextSkills.push({
        ...prev,
        id: newId,
        hash: seen.hash,
        paths: seen.paths,
      });
    }

    const filed = new Set(
      this.state.commands.flatMap((command) => ALL_IDES.flatMap((ide) => command.membership[ide] ?? []))
    );

    for (const [id, seen] of unmatchedFound) {
      added.push(id);
      nextSkills.push({
        id,
        hash: seen.hash,
        paths: seen.paths,
        deployedTo: [],
        source: 'local',
      });
      if (!filed.has(id) && !this.state.inbox.includes(id)) {
        this.state.inbox.push(id);
      }
    }

    const gone: string[] = [];
    for (const prev of this.state.skills) {
      if (matchedPrevious.has(prev.id) || nextSkills.some((record) => record.id === prev.id)) {
        continue;
      }
      gone.push(prev.id);
      this.dropSkillId(prev.id);
    }

    this.state.skills = nextSkills;

    const commandPulls = this.pullStampedCommands(gone, renameMap);

    const persistResult = this.persist();
    if (!isOk(persistResult)) {
      this.state.skills = snapshot.skills;
      this.state.inbox = snapshot.inbox;
      this.state.commands = snapshot.commands;
      return err(new Error(`Failed to save scan: ${persistResult.error.message}`));
    }

    this.writeThroughAfterScan();
    return ok({ added, gone, changed, commandPulls });
  }

  skills(): SkillRecord[] {
    return [...this.state.skills];
  }

  private dropSkillId(id: string): void {
    this.state.inbox = this.state.inbox.filter((entry) => entry !== id);
    for (const command of this.state.commands) {
      for (const ide of ALL_IDES) {
        const list = command.membership[ide];
        if (list) {
          command.membership[ide] = list.filter((skillId) => skillId !== id);
        }
      }
    }
  }

  private commandsFiling(skillId: string): Array<{ ide: IDE; name: string }> {
    const filed: Array<{ ide: IDE; name: string }> = [];
    for (const command of this.state.commands) {
      for (const ide of ALL_IDES) {
        if (command.membership[ide]?.includes(skillId)) {
          filed.push({ ide, name: command.name });
        }
      }
    }
    return filed;
  }

  /**
   * Deletes this skill’s files under `folder`, leaves nested skill
   * folders, then prunes empty parents up to the IDE skills root.
   */
  private removeSkillFolder(folder: string): Result<string[]> {
    const nested = this.fs.findSkillFolders(folder);
    if (!isOk(nested)) {
      return nested;
    }
    const keep = nested.value.filter((path) => path !== folder);

    const files = this.fs.listAllFiles(folder);
    if (!isOk(files)) {
      return files;
    }

    const muted: string[] = [];
    for (const file of files.value) {
      if (keep.some((skillDir) => file === `${skillDir}/SKILL.md` || file.startsWith(`${skillDir}/`))) {
        continue;
      }
      const removed = this.fs.removeFile(file);
      if (!isOk(removed)) {
        return removed;
      }
      muted.push(file);
    }

    const root = skillRootOf(folder);
    const candidates = new Set<string>(muted.map(parentDir).filter((dir) => dir !== ''));
    let dir: string | undefined = folder;
    while (dir && root && dir !== root) {
      candidates.add(dir);
      dir = parentDir(dir);
    }

    const deepestFirst = [...candidates].sort((a, b) => b.length - a.length);
    for (const emptyDir of deepestFirst) {
      if (!root || emptyDir === root || !emptyDir.startsWith(`${root}/`)) {
        continue;
      }
      const remaining = this.fs.listAllFiles(emptyDir);
      if (!isOk(remaining) || remaining.value.length > 0) {
        continue;
      }
      const removed = this.fs.removeDir(emptyDir);
      if (!isOk(removed)) {
        return removed;
      }
      muted.push(emptyDir);
    }

    return ok(muted);
  }

  private renameSkillId(fromId: string, toId: string): void {
    this.state.inbox = this.state.inbox.map((entry) => (entry === fromId ? toId : entry));
    for (const command of this.state.commands) {
      for (const ide of ALL_IDES) {
        const list = command.membership[ide];
        if (list) {
          command.membership[ide] = list.map((skillId) => (skillId === fromId ? toId : skillId));
        }
      }
    }
  }

  private pullStampedCommands(gone: string[], renameMap: Map<string, string>): Array<{ ide: IDE; name: string }> {
    const catalog = new Set(this.state.skills.map((record) => record.id));
    const goneSet = new Set(gone);
    const pulls: Array<{ ide: IDE; name: string }> = [];

    for (const ide of ALL_IDES) {
      const listed = this.fs.listFiles(COMMAND_DIR_BY_IDE[ide]);
      if (!isOk(listed)) {
        continue;
      }

      for (const path of listed.value) {
        if (!path.endsWith('.md')) {
          continue;
        }
        const name = path.slice(path.lastIndexOf('/') + 1, -'.md'.length);
        if (name === '') {
          continue;
        }
        const contents = this.fs.readFile(path);
        if (!isOk(contents) || !isSkilStamped(contents.value)) {
          continue;
        }
        const parsed = parseStampedSkills(contents.value);
        if (parsed === null) {
          continue;
        }
        const remapped = parsed.map((id) => renameMap.get(id) ?? id);

        let record = this.state.commands.find((command) => command.name === name);
        const previous = record ? [...(record.membership[ide] ?? [])] : undefined;
        const adopted = remapped.filter((id) => !goneSet.has(id) || catalog.has(id));
        const hadKey = record !== undefined && hasMembership(record, ide);
        const sameList = hadKey && listsEqual(previous ?? [], adopted);
        if (sameList) {
          continue;
        }

        if (!record) {
          record = {
            name,
            membership: {},
            createdAt: new Date().toISOString(),
          };
          this.state.commands.push(record);
        }
        record.membership[ide] = adopted;
        pulls.push({ ide, name });
      }
    }

    return pulls;
  }

  /**
   * Rewrite stamped command files for `ide` and `names`. Refreshes
   * frontmatter and `## Skills`; keeps Goal/Sequence/Rules. Skips
   * unstamped existing files. Removes our stamp when that IDE no
   * longer has the command.
   */
  writeThrough(ide: IDE, names: string[], dest?: string): string[] {
    const written: string[] = [];
    for (const name of names) {
      const path = underRoot(dest, `${COMMAND_DIR_BY_IDE[ide]}/${name}.md`);
      const existing = this.fs.readFile(path);
      if (isOk(existing) && !isSkilStamped(existing.value)) {
        continue;
      }

      const record = this.state.commands.find((command) => command.name === name);
      const skills = record?.membership[ide];
      if (skills === undefined) {
        if (isOk(existing) && isSkilStamped(existing.value)) {
          const removed = this.fs.removeFile(path);
          if (isOk(removed)) {
            written.push(path);
          }
        }
        continue;
      }

      const result = this.fs.writeFile(
        path,
        writeCommandFile(name, skills, isOk(existing) ? existing.value : undefined)
      );
      if (isOk(result)) {
        written.push(path);
      }
    }
    this.writtenPaths = written;
    return written;
  }

  /**
   * After scan: rewrite existing stamps when membership no longer matches.
   * Skip when the stamp already has the current list (including a stamp
   * just adopted from disk). Gone-id cleanup that dropped a skill makes
   * the lists differ, so that stamp is rewritten.
   */
  writeThroughAfterScan(): void {
    const written: string[] = [];

    for (const ide of ALL_IDES) {
      const listed = this.fs.listFiles(COMMAND_DIR_BY_IDE[ide]);
      if (!isOk(listed)) {
        continue;
      }

      for (const path of listed.value) {
        if (!path.endsWith('.md')) {
          continue;
        }
        const contents = this.fs.readFile(path);
        if (!isOk(contents) || !isSkilStamped(contents.value)) {
          continue;
        }
        const name = path.slice(path.lastIndexOf('/') + 1, -'.md'.length);
        const membership = this.state.commands.find((command) => command.name === name)?.membership[ide];
        const stampSkills = parseStampedSkills(contents.value) ?? [];
        const current = membership ?? [];
        if (listsEqual(current, stampSkills)) {
          continue;
        }
        written.push(...this.writeThrough(ide, [name]));
      }
    }
    this.writtenPaths = written;
  }

  private recordLocalDeploy(skillId: string, targetIDE: IDE, dest: string): void {
    const existingIndex = this.state.skills.findIndex((skill) => skill.id === skillId);
    const previous = existingIndex >= 0 ? this.state.skills[existingIndex] : undefined;
    if (!previous || existingIndex < 0) {
      return;
    }

    this.state.skills[existingIndex] = {
      ...previous,
      hash: hashSkillAt(this.fs, dest) ?? previous.hash,
      paths: previous.paths.includes(dest) ? previous.paths : [...previous.paths, dest],
      deployedTo: upsertDeploy(previous.deployedTo, {
        ide: targetIDE,
        path: dest,
        installedAt: new Date().toISOString(),
      }),
    };
  }

  private unstampedConflicts(
    names: string[],
    ide: IDE,
    dest?: string
  ): Array<{ name: string; path: string }> {
    const conflicts: Array<{ name: string; path: string }> = [];
    for (const name of names) {
      const path = commandFilePath(ide, name, dest);
      const existing = this.fs.readFile(path);
      if (isOk(existing) && !isSkilStamped(existing.value)) {
        conflicts.push({ name, path });
      }
    }
    return conflicts;
  }

  /** Writes state to disk. Returns an error Result if the write fails; callers must check it rather than assume the mutation was saved. */
  private persist(): Result<void> {
    this.state.version = STATE_VERSION;
    return this.fs.writeJSON(STATE_PATH, this.state);
  }

  /**
   * Picks up skills already installed by external tooling (e.g. a bare
   * `npx skills add` run outside skil) so state stays in sync.
   * In-memory only: persisted on the next mutation, not on construction.
   */
  private mergeExternallyInstalledSkills(): void {
    const known = new Set(this.state.installedSkills.map((s) => s.id));
    for (const skill of this.skillsAdapter.getInstalled()) {
      if (!known.has(skill.id)) {
        this.state.installedSkills.push(skill);
        known.add(skill.id);
      }
    }
  }
}

function listsEqual(a: string[], b: string[]): boolean {
  return a.length === b.length && a.every((id, index) => id === b[index]);
}

function catalogId(folder: string, root: string): string {
  if (folder === root) {
    return '.';
  }
  const prefix = `${root}/`;
  return folder.startsWith(prefix) ? folder.slice(prefix.length) : folder;
}

function skillRootOf(path: string): (typeof SKILL_ROOTS)[number] | undefined {
  return SKILL_ROOTS.find((root) => path === root || path.startsWith(`${root}/`));
}

function parentDir(path: string): string {
  const normalized = path.replace(/\\/g, '/').replace(/\/+$/, '');
  const index = normalized.lastIndexOf('/');
  return index <= 0 ? '' : normalized.slice(0, index);
}

function cloneSkillRecord(record: SkillRecord | undefined): SkillRecord | undefined {
  if (!record) {
    return undefined;
  }
  return {
    ...record,
    paths: [...record.paths],
    deployedTo: record.deployedTo.map((entry) => ({ ...entry })),
  };
}

function hashSkillAt(fs: IFileSystemAdapter, folder: string): string | undefined {
  const contents = fs.readFile(`${folder}/SKILL.md`);
  if (!isOk(contents)) {
    return undefined;
  }
  return createHash('sha256').update(contents.value, 'utf8').digest('hex');
}

function upsertDeploy(
  existing: SkillRecord['deployedTo'],
  entry: SkillRecord['deployedTo'][number]
): SkillRecord['deployedTo'] {
  const index = existing.findIndex((deploy) => deploy.ide === entry.ide);
  if (index === -1) {
    return [...existing, entry];
  }
  return existing.map((deploy, i) => (i === index ? entry : deploy));
}
