import { Option, type Command } from 'commander';
import type { ICollectionEngine } from '../../interfaces/engine.js';
import { isOk } from '../../core/result.js';
import type { IDE } from '../../types/index.js';
import { TARGET_IDES } from '../ides.js';
import { printOutcome, type CommandOutcome } from '../output.js';

export async function runCopy(
  engine: ICollectionEngine,
  name: string,
  fromIde: IDE,
  toIde: IDE,
  opts?: { replace?: boolean }
): Promise<CommandOutcome> {
  const result = await engine.copyTo(name, fromIde, toIde, opts);
  if (!isOk(result)) {
    return { message: result.error.message, isError: true };
  }
  if (result.value.failures.length > 0) {
    return { message: result.value.failures.join('\n'), isError: true };
  }
  return { message: `Copied command '${name}' from ${fromIde} to ${toIde}`, isError: false };
}

export async function runCopyAll(
  engine: ICollectionEngine,
  fromIde: IDE,
  toIde: IDE,
  opts?: { replace?: boolean }
): Promise<CommandOutcome> {
  const result = await engine.copyAll(fromIde, toIde, opts);
  if (!isOk(result)) {
    return { message: result.error.message, isError: true };
  }
  if (result.value.failures.length > 0) {
    return { message: result.value.failures.join('\n'), isError: true };
  }
  return { message: `Copied all commands from ${fromIde} to ${toIde}`, isError: false };
}

export function registerCopyCommand(program: Command, engine: ICollectionEngine): void {
  program
    .command('copy [command]')
    .description('Copy a command list to another IDE (stamped file + missing skills)')
    .addOption(
      new Option('--from <ide>', 'source IDE: cursor, claude, windsurf, or agents')
        .choices(TARGET_IDES)
        .makeOptionMandatory()
    )
    .addOption(
      new Option('--to <ide>', 'dest IDE: cursor, claude, windsurf, or agents')
        .choices(TARGET_IDES)
        .makeOptionMandatory()
    )
    .option('--all', 'copy every command from the source IDE')
    .option('--replace', 'overwrite an existing dest file that was not generated by skil')
    .action(async (name: string | undefined, options: { from: IDE; to: IDE; all?: boolean; replace?: boolean }) => {
      if (options.all) {
        printOutcome(await runCopyAll(engine, options.from, options.to, { replace: options.replace }));
        return;
      }
      if (!name) {
        printOutcome({ message: 'Pass a command name, or --all', isError: true });
        return;
      }
      printOutcome(await runCopy(engine, name, options.from, options.to, { replace: options.replace }));
    });
}
