import { Option, type Command } from 'commander';
import type { ICollectionEngine } from '../../interfaces/engine.js';
import { isOk } from '../../core/result.js';
import type { IDE } from '../../types/index.js';
import { printOutcome, type CommandOutcome } from '../output.js';

const TARGET_IDES = ['cursor', 'claude', 'windsurf', 'agents'] as const satisfies readonly IDE[];

function exportResultOutcome(
  result: Awaited<ReturnType<ICollectionEngine['exportCommand']>>,
  successMessage: string
): CommandOutcome {
  if (!isOk(result)) {
    return { message: result.error.message, isError: true };
  }
  if (result.value.failures.length > 0) {
    return { message: result.value.failures.join('\n'), isError: true };
  }
  return { message: successMessage, isError: false };
}

export async function runExport(
  engine: ICollectionEngine,
  name: string,
  targetIDE: IDE,
  opts?: { replace?: boolean }
): Promise<CommandOutcome> {
  return exportResultOutcome(
    await engine.exportCommand(name, targetIDE, opts),
    `Exported command '${name}' to ${targetIDE}`
  );
}

export async function runExportAll(
  engine: ICollectionEngine,
  targetIDE: IDE,
  opts?: { replace?: boolean }
): Promise<CommandOutcome> {
  return exportResultOutcome(
    await engine.exportAll(targetIDE, opts),
    `Exported all commands to ${targetIDE}`
  );
}

export function registerExportCommand(program: Command, engine: ICollectionEngine): void {
  program
    .command('export [command]')
    .description('Write stamped command files for the workspace and deploy filed skills to an IDE (not skillsmith convert)')
    .addOption(
      new Option('--to <ide>', 'target IDE: cursor, claude, windsurf, or agents')
        .choices(TARGET_IDES)
        .makeOptionMandatory()
    )
    .option('--replace', 'overwrite an existing file that was not generated by skil')
    .action(async (name: string | undefined, options: { to: IDE; replace?: boolean }) => {
      if (!name) {
        printOutcome(await runExportAll(engine, options.to, { replace: options.replace }));
        return;
      }
      printOutcome(await runExport(engine, name, options.to, { replace: options.replace }));
    });
}
