import { Option, type Command } from 'commander';
import type { ICollectionEngine } from '../../interfaces/engine.js';
import { isOk } from '../../core/result.js';
import type { IDE } from '../../types/index.js';
import { printOutcome, type CommandOutcome } from '../output.js';

const TARGET_IDES = ['cursor', 'claude', 'windsurf', 'agents'] as const satisfies readonly IDE[];

export async function runExport(
  engine: ICollectionEngine,
  name: string,
  targetIDE: IDE,
  opts?: { replace?: boolean }
): Promise<CommandOutcome> {
  const result = await engine.exportCommand(name, targetIDE, opts);
  if (!isOk(result)) {
    return { message: result.error.message, isError: true };
  }
  if (result.value.failures.length > 0) {
    return { message: result.value.failures.join('\n'), isError: true };
  }
  return { message: `Exported command '${name}' to ${targetIDE}`, isError: false };
}

export function registerExportCommand(program: Command, engine: ICollectionEngine): void {
  program
    .command('export <command>')
    .description('Write our stamped command file and deploy filed skills to an IDE (not skillsmith convert)')
    .addOption(
      new Option('--to <ide>', 'target IDE: cursor, claude, windsurf, or agents')
        .choices(TARGET_IDES)
        .makeOptionMandatory()
    )
    .option('--replace', 'overwrite an existing file that was not generated by skil')
    .action(async (name: string, options: { to: IDE; replace?: boolean }) => {
      printOutcome(await runExport(engine, name, options.to, { replace: options.replace }));
    });
}
