import { describe, expect, it } from 'vitest';
import { CollectionEngine } from '../../core/collection-engine.js';
import { InMemoryConfigAdapter } from '../../adapters/in-memory-config.js';
import { InMemoryFileSystemAdapter } from '../../adapters/in-memory-fs.js';
import { InMemorySkillsAdapter } from '../../adapters/in-memory-skills.js';
import { isOk } from '../../core/result.js';
import { createProgram } from '../program.js';
import { runExport, runExportAll } from './export.js';

function buildEngine(): {
  engine: CollectionEngine;
  fs: InMemoryFileSystemAdapter;
  skills: InMemorySkillsAdapter;
} {
  const fs = new InMemoryFileSystemAdapter();
  const skills = new InMemorySkillsAdapter();
  const engine = new CollectionEngine(fs, new InMemoryConfigAdapter(), skills);
  return { engine, fs, skills };
}

describe('runExport', () => {
  it('writes our stamped command file and copies local skills without convert or npx', async () => {
    const { engine, fs, skills } = buildEngine();
    fs.writeFile('.cursor/skills/tdd/SKILL.md', '# tdd\n');
    fs.writeFile('.cursor/skills/design/SKILL.md', '# design\n');
    engine.scan();
    engine.create('build', ['tdd', 'design']);

    const outcome = await runExport(engine, 'build', 'cursor');

    expect(outcome.isError).toBe(false);
    expect(outcome.message).toContain('build');
    expect(outcome.message).toContain('cursor');

    const written = fs.readFile('.cursor/commands/build.md');
    expect(isOk(written)).toBe(true);
    if (isOk(written)) {
      expect(written.value).toContain('generated_by: skil');
      expect(written.value).toContain('- tdd');
      expect(written.value).toContain('- design');
    }
    expect(skills.getConvertCallCount()).toBe(0);
    expect(skills.getInstalls()).toEqual([]);
  });

    it('refuses an unstamped file unless replace is set', async () => {
    const { engine, fs } = buildEngine();
    engine.create('build', ['tdd']);
    fs.writeFile('.cursor/commands/build.md', '# their old /build\n');

    const refused = await runExport(engine, 'build', 'cursor');

    expect(refused.isError).toBe(true);
    expect(refused.message).toMatch(/not generated by skil|replace/i);
    expect(fs.readFile('.cursor/commands/build.md')).toEqual({
      ok: true,
      value: '# their old /build\n',
    });

    const replaced = await runExport(engine, 'build', 'cursor', { replace: true });

    expect(replaced.isError).toBe(false);
    const written = fs.readFile('.cursor/commands/build.md');
    expect(isOk(written)).toBe(true);
    if (isOk(written)) {
      expect(written.value).toContain('generated_by: skil');
      expect(written.value).not.toContain('their old /build');
    }
  });

  it('reports an error when the command is missing', async () => {
    const { engine, fs } = buildEngine();

    const outcome = await runExport(engine, 'missing', 'cursor');

    expect(outcome.isError).toBe(true);
    expect(outcome.message).toContain("Command 'missing' not found");
    expect(isOk(fs.readFile('.cursor/commands/missing.md'))).toBe(false);
  });
});

describe('runExportAll', () => {
  it('writes stamped files for every command', async () => {
    const { engine, fs } = buildEngine();
    engine.create('build', []);
    engine.create('testing', []);

    const outcome = await runExportAll(engine, 'cursor');

    expect(outcome.isError).toBe(false);
    expect(outcome.message).toMatch(/all commands/i);
    expect(outcome.message).toContain('cursor');
    expect(isOk(fs.readFile('.cursor/commands/build.md'))).toBe(true);
    expect(isOk(fs.readFile('.cursor/commands/testing.md'))).toBe(true);
  });
});

describe('registerExportCommand', () => {
  it('requires --to and does not write a command file without it', () => {
    const { engine, fs } = buildEngine();
    engine.create('build', ['tdd']);
    fs.removeFile('.cursor/commands/build.md');
    const program = createProgram(engine);
    program.exitOverride();

    expect(() => program.parse(['export', 'build'], { from: 'user' })).toThrow();
    expect(isOk(fs.readFile('.cursor/commands/build.md'))).toBe(false);
  });

  it('rejects an unknown IDE before the engine', () => {
    const { engine, fs } = buildEngine();
    engine.create('build', ['tdd']);
    fs.removeFile('.cursor/commands/build.md');
    const program = createProgram(engine);
    program.exitOverride();

    expect(() => program.parse(['export', 'build', '--to', 'vscode'], { from: 'user' })).toThrow();
    expect(isOk(fs.readFile('.cursor/commands/build.md'))).toBe(false);
  });

  it('passes --replace through to overwrite an unstamped file', async () => {
    const { engine, fs } = buildEngine();
    engine.create('build', ['tdd']);
    fs.writeFile('.cursor/commands/build.md', '# their old /build\n');
    const program = createProgram(engine);
    program.exitOverride();

    await program.parseAsync(['export', 'build', '--to', 'cursor', '--replace'], { from: 'user' });

    const written = fs.readFile('.cursor/commands/build.md');
    expect(isOk(written)).toBe(true);
    if (isOk(written)) {
      expect(written.value).toContain('generated_by: skil');
      expect(written.value).not.toContain('their old /build');
    }
  });

  it('exports every command when no command name is given', async () => {
    const { engine, fs } = buildEngine();
    engine.create('build', []);
    engine.create('testing', []);
    const program = createProgram(engine);
    program.exitOverride();

    await program.parseAsync(['export', '--to', 'cursor'], { from: 'user' });

    expect(isOk(fs.readFile('.cursor/commands/build.md'))).toBe(true);
    expect(isOk(fs.readFile('.cursor/commands/testing.md'))).toBe(true);
  });
});
