import { cloneElement, isValidElement, useCallback, useEffect, useMemo, useRef, useState, type KeyboardEvent, type ReactElement, type ReactNode } from 'react';
import { ArrowLeft, CaretDown, CaretLeft, CaretRight, Check, CircleNotch, Copy, FloppyDisk, Plus, Trash, X } from '@phosphor-icons/react';
import { useBridge } from '../bridge-context';
import { FOCUS_RING } from '../lib/focus-ring';
import { groupCommandsByStage } from '../lib/sdlc';
import type { Collection, IDE } from '../../../shared/ipc';
import { targetPhrase } from './InstallSkill';
import { StatusDialog } from './StatusDialog';
import { IDE_OPTIONS } from './InstallSkill';
import { CommandFormatContext, FORMAT_LABELS } from './format-context';

function otherIde(ide: IDE): IDE {
  return IDE_OPTIONS.find((option) => option !== ide) ?? 'claude';
}

const INBOX_PAGE_SIZE = 10;

type IdeSummary = { commands: number; skills: number };

const EMPTY_SUMMARIES: Record<IDE, IdeSummary> = {
  cursor: { commands: 0, skills: 0 },
  claude: { commands: 0, skills: 0 },
  windsurf: { commands: 0, skills: 0 },
  agents: { commands: 0, skills: 0 },
};

function uniqueSkillCount(collections: Collection[]): number {
  return new Set(collections.flatMap((collection) => collection.skills)).size;
}

type ExportOutcome =
  | { status: 'loading'; ide: IDE; dest?: string }
  | { status: 'success'; ide: IDE; dest?: string; path?: string }
  | { status: 'error'; ide: IDE; dest?: string; message: string; summary?: string };

function matchesQuery(skillId: string, query: string): boolean {
  const needle = query.trim().toLowerCase();
  return needle.length === 0 || skillId.toLowerCase().includes(needle);
}

function isUnstampedConflict(message: string): boolean {
  return /not generated by skil/i.test(message);
}

function CollectionDetail({
  collection,
  inbox,
  ide,
  onChange,
  onDeleted,
}: {
  collection: Collection;
  inbox: string[];
  ide: IDE;
  onChange: () => void;
  onDeleted: () => void;
}) {
  const bridge = useBridge();
  const [error, setError] = useState<string | null>(null);
  const [confirmDelete, setConfirmDelete] = useState(false);
  const [inboxOpen, setInboxOpen] = useState(true);
  const [inboxQuery, setInboxQuery] = useState('');
  const [inboxPage, setInboxPage] = useState(0);
  const inboxPickerId = `inbox-picker-${collection.name}`;

  const inboxMatches = useMemo(
    () => inbox.filter((skillId) => matchesQuery(skillId, inboxQuery)),
    [inbox, inboxQuery]
  );
  const inboxPageCount = inboxMatches.length > 0 ? Math.ceil(inboxMatches.length / INBOX_PAGE_SIZE) : 0;
  const safeInboxPage = inboxPageCount === 0 ? 0 : Math.min(inboxPage, inboxPageCount - 1);
  const visibleInbox = inboxMatches.slice(safeInboxPage * INBOX_PAGE_SIZE, (safeInboxPage + 1) * INBOX_PAGE_SIZE);

  async function handleAddFromInbox(skillId: string) {
    setError(null);
    const result = await bridge.addSkill(collection.name, skillId, ide);
    if (!result.ok) {
      setError(result.error.message);
      return;
    }
    onChange();
  }

  async function handleRemoveSkill(skillId: string) {
    setError(null);
    const result = await bridge.removeSkillFromCollection(collection.name, skillId, ide);
    if (!result.ok) {
      setError(result.error.message);
      return;
    }
    onChange();
  }

  async function handleDelete() {
    setError(null);
    const result = await bridge.deleteCollection(collection.name, ide);
    if (!result.ok) {
      setError(result.error.message);
      setConfirmDelete(false);
      return;
    }
    setConfirmDelete(false);
    onDeleted();
  }

  return (
    <section className="detail-panel panel-section" aria-label={`Command ${collection.name} details`}>
      <div className="detail-header">
        <div>
          <p className="eyebrow">Command</p>
          <h2>/{collection.name}</h2>
          <p className="muted-copy">
            {collection.skills.length === 1 ? '1 skill' : `${collection.skills.length} skills`}
          </p>
        </div>
        <div className="detail-actions">
          <button
            type="button"
            onClick={() => setConfirmDelete(true)}
            aria-label={`Delete ${collection.name}`}
            className={`delete-card detail-delete ${FOCUS_RING}`}
          >
            <Trash size={16} weight="regular" aria-hidden="true" />
          </button>
        </div>
      </div>

      {error && (
        <p role="alert" className="rounded-md border border-destructive/40 bg-destructive/10 px-3 py-2 text-sm text-destructive">
          {error}
        </p>
      )}

      <div className="active-skills">
        <div className="subheading">
          <span>Included skills</span>
          <span className="count-pill">{collection.skills.length}</span>
        </div>
        {collection.skills.length === 0 && <p className="muted-copy">No skills in this command yet</p>}
        {collection.skills.map((skillId) => (
          <div className="included-skill" key={skillId}>
            <span>{skillId}</span>
            <div className="skill-actions">
              <button
                type="button"
                onClick={() => handleRemoveSkill(skillId)}
                aria-label={`Remove ${skillId}`}
                className={FOCUS_RING}
              >
                <X size={14} weight="regular" />
              </button>
            </div>
          </div>
        ))}
      </div>

      {inbox.length > 0 && (
        <div className="active-skills inbox-picker">
          <button
            type="button"
            className={`inbox-toggle ${FOCUS_RING}`}
            aria-expanded={inboxOpen}
            aria-controls={inboxPickerId}
            aria-label={`From Inbox, ${inbox.length === 1 ? '1 skill' : `${inbox.length} skills`}`}
            onClick={() => setInboxOpen((open) => !open)}
          >
            <span>From Inbox</span>
            <span className="count-pill">{inbox.length}</span>
            <CaretDown className="inbox-caret" size={14} weight="regular" aria-hidden="true" />
          </button>
          <div id={inboxPickerId} hidden={!inboxOpen} className="inbox-picker-list">
            <label className="search-box inbox-filter" htmlFor={`inbox-filter-${collection.name}`}>
              <span className="sr-only">Filter inbox</span>
              <input
                id={`inbox-filter-${collection.name}`}
                value={inboxQuery}
                onChange={(event) => {
                  setInboxQuery(event.target.value);
                  setInboxPage(0);
                }}
                placeholder="Filter inbox"
              />
            </label>
            {visibleInbox.length === 0 ? (
              <p className="muted-copy">No matching skills</p>
            ) : (
              visibleInbox.map((skillId) => {
                const added = collection.skills.includes(skillId);
                return (
                  <div className="library-skill" key={skillId}>
                    <div className="skill-info">
                      <div className="skill-name">{skillId}</div>
                    </div>
                    <button
                      type="button"
                      onClick={() => void handleAddFromInbox(skillId)}
                      aria-label={added ? `Added ${skillId}` : `Add ${skillId} to ${collection.name}`}
                      aria-pressed={added}
                      className={`add-icon-button ${FOCUS_RING}`}
                    >
                      {added ? (
                        <Check size={16} weight="regular" aria-hidden="true" />
                      ) : (
                        <Plus size={16} weight="regular" aria-hidden="true" />
                      )}
                    </button>
                  </div>
                );
              })
            )}
            {inboxPageCount > 1 && (
              <nav aria-label="Inbox pages" className="page-row">
                <button
                  type="button"
                  aria-label="Previous inbox page"
                  disabled={safeInboxPage === 0}
                  onClick={() => setInboxPage(safeInboxPage - 1)}
                  className={`filter ${FOCUS_RING}`}
                >
                  <CaretLeft size={14} weight="regular" aria-hidden="true" />
                </button>
                <span className="page-status">
                  Page {safeInboxPage + 1} of {inboxPageCount}
                </span>
                <button
                  type="button"
                  aria-label="Next inbox page"
                  disabled={safeInboxPage === inboxPageCount - 1}
                  onClick={() => setInboxPage(safeInboxPage + 1)}
                  className={`filter ${FOCUS_RING}`}
                >
                  <CaretRight size={14} weight="regular" aria-hidden="true" />
                </button>
              </nav>
            )}
          </div>
        </div>
      )}

      {confirmDelete && (
        <div className="modal-backdrop" role="presentation" onClick={() => setConfirmDelete(false)}>
          <div
            className="help-modal"
            role="dialog"
            aria-modal="true"
            aria-labelledby="delete-collection-title"
            onClick={(event) => event.stopPropagation()}
          >
            <p className="eyebrow">Commands</p>
            <h2 id="delete-collection-title">Delete {collection.name}?</h2>
            <p className="muted-copy">This cannot be undone.</p>
            <div className="modal-actions">
              <button type="button" className={`outline-button ${FOCUS_RING}`} onClick={() => setConfirmDelete(false)}>
                Cancel
              </button>
              <button type="button" className={`primary-button ${FOCUS_RING}`} onClick={() => void handleDelete()}>
                Delete command
              </button>
            </div>
          </div>
        </div>
      )}
    </section>
  );
}

function selectCollection(event: KeyboardEvent<HTMLLIElement>, name: string, onSelect: (name: string) => void) {
  if (event.key === 'Enter' || event.key === ' ') {
    event.preventDefault();
    onSelect(name);
  }
}

function IdeOverview({
  summaries,
  onOpen,
}: {
  summaries: Record<IDE, IdeSummary>;
  onOpen: (ide: IDE) => void;
}) {
  return (
    <section className="collections-panel panel-section">
      <div className="section-heading">
        <div>
          <p className="eyebrow">Workspace</p>
          <h1>Commands</h1>
          <p className="workspace-lede">Pick an IDE, then file inbox skills onto its commands.</p>
        </div>
      </div>
      <div className="ide-card-grid">
        {IDE_OPTIONS.map((ide) => {
          const summary = summaries[ide];
          return (
            <button
              key={ide}
              type="button"
              className={`ide-workspace-card glass-panel ${FOCUS_RING}`}
              aria-label={`Open ${FORMAT_LABELS[ide]} workspace`}
              onClick={() => onOpen(ide)}
            >
              <h2>{FORMAT_LABELS[ide]}</h2>
              <p className="found-value">{summary.commands}</p>
              <p className="found-label">{summary.commands === 1 ? 'command' : 'commands'}</p>
              <p className="ide-card-skills">
                {summary.skills === 1 ? '1 skill' : `${summary.skills} skills`}
              </p>
            </button>
          );
        })}
      </div>
    </section>
  );
}

function CollectionsPanel({
  children,
  formatIde,
  copyDest,
  onCopyDestChange,
  onBack,
  onSave,
  onCopy,
  onCopyAll,
  isBusy,
  canSave,
  canCopy,
  selectedName,
}: {
  children: ReactNode;
  formatIde: IDE;
  copyDest: IDE;
  onCopyDestChange: (ide: IDE) => void;
  onBack: () => void;
  onSave: () => void;
  onCopy: () => void;
  onCopyAll: () => void;
  isBusy: boolean;
  canSave: boolean;
  canCopy: boolean;
  selectedName: string | null;
}) {
  const dests = IDE_OPTIONS.filter((option) => option !== formatIde);

  return (
    <section className="collections-panel panel-section">
      <div className="section-heading">
        <div>
          <div className="workspace-title-row">
            <button
              type="button"
              onClick={onBack}
              aria-label="Back to IDEs"
              title="Back to IDEs"
              className={`icon-button ${FOCUS_RING}`}
            >
              <ArrowLeft size={16} weight="regular" aria-hidden="true" />
            </button>
            <div>
              <p className="eyebrow">{FORMAT_LABELS[formatIde]}</p>
              <h1>Commands</h1>
            </div>
          </div>
          <p className="workspace-lede">Named SDLC knobs. File inbox skills onto them, then export.</p>
        </div>
        <div className="library-heading-actions">
          <button
            type="button"
            onClick={onSave}
            disabled={!canSave || isBusy}
            aria-label="Save"
            title="Save"
            aria-busy={isBusy || undefined}
            className={`icon-button ${FOCUS_RING}`}
          >
            {isBusy ? (
              <CircleNotch size={16} weight="regular" className="spin" aria-hidden="true" />
            ) : (
              <FloppyDisk size={16} weight="regular" aria-hidden="true" />
            )}
          </button>
        </div>
      </div>
      <div className="copy-bar">
        <p className="copy-bar-label">Copy to</p>
        <div className="copy-bar-body">
          <div className="copy-dests" role="group" aria-label="Copy to">
            {dests.map((ide) => (
              <button
                key={ide}
                type="button"
                aria-pressed={copyDest === ide}
                disabled={isBusy}
                className={`copy-dest ${FOCUS_RING}`}
                onClick={() => onCopyDestChange(ide)}
              >
                {FORMAT_LABELS[ide]}
              </button>
            ))}
          </div>
          <div className="copy-bar-actions">
            <button
              type="button"
              onClick={onCopy}
              disabled={!canCopy || isBusy}
              aria-label={`Copy ${selectedName ?? 'command'} to ${FORMAT_LABELS[copyDest]}`}
              className={`outline-button ${FOCUS_RING}`}
            >
              <Copy size={14} weight="regular" aria-hidden="true" />
              Copy
            </button>
            <button
              type="button"
              onClick={onCopyAll}
              disabled={!canSave || isBusy}
              aria-label={`Copy all to ${FORMAT_LABELS[copyDest]}`}
              className={`outline-button ${FOCUS_RING}`}
            >
              Copy all
            </button>
          </div>
        </div>
      </div>
      {children}
    </section>
  );
}

export default function CollectionList({ children }: { children?: ReactNode }) {
  const bridge = useBridge();
  const [collections, setCollections] = useState<Collection[] | null>(null);
  const [inbox, setInbox] = useState<string[]>([]);
  const [selectedName, setSelectedName] = useState<string | null>(null);
  const [workspaceIde, setWorkspaceIde] = useState<IDE | null>(null);
  const [summaries, setSummaries] = useState<Record<IDE, IdeSummary>>(EMPTY_SUMMARIES);
  const [copyDest, setCopyDest] = useState<IDE>('claude');
  const formatIde = workspaceIde ?? 'cursor';
  const [exportOutcome, setExportOutcome] = useState<ExportOutcome | null>(null);
  const [copyOutcome, setCopyOutcome] = useState<ExportOutcome | null>(null);
  const [confirmReplace, setConfirmReplace] = useState(false);
  const [confirmCopyReplace, setConfirmCopyReplace] = useState(false);
  const [pendingCopyAll, setPendingCopyAll] = useState(false);
  const [exportDest, setExportDest] = useState<string | undefined>();
  const refreshId = useRef(0);
  const isBusy = exportOutcome?.status === 'loading' || copyOutcome?.status === 'loading';

  const refresh = useCallback(async () => {
    const id = ++refreshId.current;
    const [nextInbox, ...lists] = await Promise.all([
      bridge.listInbox(),
      ...IDE_OPTIONS.map((ide) => bridge.listCollections(ide)),
    ]);
    if (id !== refreshId.current) return;
    setInbox(nextInbox);
    setSummaries(
      Object.fromEntries(
        IDE_OPTIONS.map((ide, index) => [
          ide,
          { commands: lists[index].length, skills: uniqueSkillCount(lists[index]) },
        ])
      ) as Record<IDE, IdeSummary>
    );
    if (!workspaceIde) {
      setCollections(null);
      setSelectedName(null);
      return;
    }
    const next = lists[IDE_OPTIONS.indexOf(workspaceIde)];
    setCollections(next);
    setSelectedName((current) => {
      if (current && next.some((collection) => collection.name === current)) return current;
      return next[0]?.name ?? null;
    });
  }, [bridge, workspaceIde]);

  useEffect(() => {
    void refresh();
  }, [refresh]);

  async function handleExport(replace?: boolean) {
    setConfirmReplace(false);
    const root = await bridge.getProjectRoot();
    let dest: string | undefined;
    if (!root) {
      dest = replace ? exportDest : undefined;
      if (dest === undefined) {
        const picked = await bridge.pickDestinationFolder();
        if (picked === null) return;
        dest = picked;
        setExportDest(picked);
      }
    }
    const target = dest ?? root ?? undefined;
    if (!workspaceIde) return;
    setExportOutcome({ status: 'loading', ide: workspaceIde, dest: target });
    const result = await bridge.exportAll(workspaceIde, {
      ...(replace ? { replace: true } : {}),
      ...(dest ? { dest } : {}),
    });

    if (!result.ok) {
      if (isUnstampedConflict(result.error.message)) {
        setExportOutcome(null);
        setConfirmReplace(true);
        return;
      }
      setExportDest(undefined);
      setExportOutcome({ status: 'error', ide: workspaceIde, dest: target, message: result.error.message });
      return;
    }
    setExportDest(undefined);
    setConfirmReplace(false);
    if (result.value.failures.length > 0) {
      setExportOutcome({
        status: 'error',
        ide: workspaceIde,
        dest: target,
        summary: `Exported the command files, but some skills did not deploy to ${targetPhrase(workspaceIde, target)}`,
        message: result.value.failures.join('\n'),
      });
      return;
    }
    setExportOutcome({
      status: 'success',
      ide: workspaceIde,
      dest: target,
      path: result.value.succeeded[0],
    });
  }

  async function handleCopy(all: boolean, replace?: boolean) {
    setConfirmCopyReplace(false);
    const root = await bridge.getProjectRoot();
    let dest: string | undefined;
    if (!root) {
      const picked = await bridge.pickDestinationFolder();
      if (picked === null) return;
      dest = picked;
    }
    const target = dest ?? root ?? undefined;
    setCopyOutcome({ status: 'loading', ide: copyDest, dest: target });
    const opts = {
      ...(replace ? { replace: true } : {}),
      ...(dest ? { dest } : {}),
    };
    if (!workspaceIde) return;
    const result = all
      ? await bridge.copyAll(workspaceIde, copyDest, opts)
      : selectedName
        ? await bridge.copyTo(selectedName, workspaceIde, copyDest, opts)
        : { ok: false as const, error: new Error('Select a command to copy') };

    if (!result.ok) {
      if (isUnstampedConflict(result.error.message)) {
        setCopyOutcome(null);
        setPendingCopyAll(all);
        setConfirmCopyReplace(true);
        return;
      }
      setCopyOutcome({ status: 'error', ide: copyDest, dest: target, message: result.error.message });
      return;
    }
    if (result.value.failures.length > 0) {
      setCopyOutcome({
        status: 'error',
        ide: copyDest,
        dest: target,
        summary: `Copied, but some skills did not deploy to ${targetPhrase(copyDest, target)}`,
        message: result.value.failures.join('\n'),
      });
      return;
    }
    setCopyOutcome({
      status: 'success',
      ide: copyDest,
      dest: target,
      path: result.value.succeeded[0],
    });
    await refresh();
  }

  function openWorkspace(ide: IDE) {
    setWorkspaceIde(ide);
    setCopyDest(otherIde(ide));
  }

  const createSlot = isValidElement(children)
    ? cloneElement(children as ReactElement<{ onCreated?: (collection: Collection) => void }>, {
        onCreated: () => {
          void refresh();
        },
      })
    : children;

  const panel = workspaceIde ? (
    <CollectionsPanel
      formatIde={workspaceIde}
      copyDest={copyDest}
      onCopyDestChange={setCopyDest}
      onBack={() => setWorkspaceIde(null)}
      onSave={() => void handleExport()}
      onCopy={() => void handleCopy(false)}
      onCopyAll={() => void handleCopy(true)}
      isBusy={isBusy}
      canSave={(collections?.length ?? 0) > 0}
      canCopy={selectedName !== null}
      selectedName={selectedName}
    >
      {collections === null ? null : collections.length === 0 ? (
        <p className="muted-copy">No commands yet</p>
      ) : (
        <div className="command-stages">
          {groupCommandsByStage(collections).map((stage) => (
            <div className="command-stage" key={stage.key}>
              {stage.label && <p className="stage-label">{stage.label}</p>}
              <ul className="collection-list">
                {stage.commands.map((collection) => (
                  <li
                    key={collection.name}
                    aria-label={`Command ${collection.name}`}
                    aria-current={collection.name === selectedName ? 'true' : undefined}
                    className={`collection-card ${collection.name === selectedName ? 'selected' : ''}`}
                    tabIndex={0}
                    onClick={() => setSelectedName(collection.name)}
                    onKeyDown={(event) => selectCollection(event, collection.name, setSelectedName)}
                  >
                    <div className="card-title">
                      <span>/{collection.name}</span>
                    </div>
                    <div className="skill-count">
                      <span>
                        {collection.skills.length} {collection.skills.length === 1 ? 'skill' : 'skills'}
                      </span>
                    </div>
                  </li>
                ))}
              </ul>
            </div>
          ))}
        </div>
      )}
      {createSlot}
    </CollectionsPanel>
  ) : (
    <IdeOverview summaries={summaries} onOpen={openWorkspace} />
  );

  const selected =
    workspaceIde && collections ? (collections.find((collection) => collection.name === selectedName) ?? null) : null;

  return (
    <CommandFormatContext.Provider value={formatIde}>
      {panel}
      {selected && workspaceIde && (
        <CollectionDetail
          key={`${formatIde}:${selected.name}`}
          collection={selected}
          inbox={inbox}
          ide={formatIde}
          onChange={refresh}
          onDeleted={refresh}
        />
      )}
      {exportOutcome && (
        <StatusDialog
          eyebrow="Export"
          title={
            exportOutcome.status === 'loading'
              ? 'Exporting…'
              : exportOutcome.status === 'success'
                ? 'Exported'
                : 'Export failed'
          }
          kind={exportOutcome.status}
          errorDetail={exportOutcome.status === 'error' ? exportOutcome.message : undefined}
          closeLabel="Close export status"
          onClose={() => setExportOutcome(null)}
        >
          {exportOutcome.status === 'loading' && (
            <p role="status" className="muted-copy">
              Exporting all commands to {targetPhrase(exportOutcome.ide, exportOutcome.dest)}
            </p>
          )}
          {exportOutcome.status === 'success' && (
            <>
              <p className="status-copy-success">{`Exported all commands to ${targetPhrase(exportOutcome.ide, exportOutcome.dest)}`}</p>
              {exportOutcome.path && <p className="status-path">{exportOutcome.path}</p>}
            </>
          )}
          {exportOutcome.status === 'error' && (
            <p role="alert" className="muted-copy text-destructive">
              {exportOutcome.summary ??
                `Could not export commands to ${targetPhrase(exportOutcome.ide, exportOutcome.dest)}`}
            </p>
          )}
        </StatusDialog>
      )}
      {copyOutcome && (
        <StatusDialog
          eyebrow="Copy"
          title={
            copyOutcome.status === 'loading'
              ? 'Copying…'
              : copyOutcome.status === 'success'
                ? 'Copied'
                : 'Copy failed'
          }
          kind={copyOutcome.status}
          errorDetail={copyOutcome.status === 'error' ? copyOutcome.message : undefined}
          closeLabel="Close copy status"
          onClose={() => setCopyOutcome(null)}
        >
          {copyOutcome.status === 'loading' && (
            <p role="status" className="muted-copy">
              Copying to {targetPhrase(copyOutcome.ide, copyOutcome.dest)}
            </p>
          )}
          {copyOutcome.status === 'success' && (
            <>
              <p className="status-copy-success">{`Copied to ${targetPhrase(copyOutcome.ide, copyOutcome.dest)}`}</p>
              {copyOutcome.path && <p className="status-path">{copyOutcome.path}</p>}
            </>
          )}
          {copyOutcome.status === 'error' && (
            <p role="alert" className="muted-copy text-destructive">
              {copyOutcome.summary ?? `Could not copy to ${targetPhrase(copyOutcome.ide, copyOutcome.dest)}`}
            </p>
          )}
        </StatusDialog>
      )}
      {confirmReplace && (
        <div className="modal-backdrop" role="presentation" onClick={() => setConfirmReplace(false)}>
          <div
            className="help-modal"
            role="dialog"
            aria-modal="true"
            aria-labelledby="replace-export-title"
            onClick={(event) => event.stopPropagation()}
          >
            <p className="eyebrow">Export</p>
            <h2 id="replace-export-title">Replace existing file?</h2>
            <p className="muted-copy">
              A command file exists and was not generated by skil. Replace it with our command template?
            </p>
            <div className="modal-actions">
              <button type="button" className={`outline-button ${FOCUS_RING}`} onClick={() => setConfirmReplace(false)}>
                Cancel
              </button>
              <button type="button" className={`primary-button ${FOCUS_RING}`} onClick={() => void handleExport(true)}>
                Replace
              </button>
            </div>
          </div>
        </div>
      )}
      {confirmCopyReplace && (
        <div className="modal-backdrop" role="presentation" onClick={() => setConfirmCopyReplace(false)}>
          <div
            className="help-modal"
            role="dialog"
            aria-modal="true"
            aria-labelledby="replace-copy-title"
            onClick={(event) => event.stopPropagation()}
          >
            <p className="eyebrow">Copy</p>
            <h2 id="replace-copy-title">Replace existing file?</h2>
            <p className="muted-copy">
              A command file exists and was not generated by skil. Replace it with our command template?
            </p>
            <div className="modal-actions">
              <button type="button" className={`outline-button ${FOCUS_RING}`} onClick={() => setConfirmCopyReplace(false)}>
                Cancel
              </button>
              <button
                type="button"
                className={`primary-button ${FOCUS_RING}`}
                onClick={() => void handleCopy(pendingCopyAll, true)}
              >
                Replace
              </button>
            </div>
          </div>
        </div>
      )}
    </CommandFormatContext.Provider>
  );
}
