import { cloneElement, isValidElement, useCallback, useEffect, useMemo, useRef, useState, type KeyboardEvent, type ReactElement, type ReactNode } from 'react';
import { CaretDown, CaretLeft, CaretRight, Check, CircleNotch, DownloadSimple, Plus, Trash, X } from '@phosphor-icons/react';
import { useBridge } from '../bridge-context';
import { FOCUS_RING } from '../lib/focus-ring';
import { parseConflictedCommandNames } from '../lib/command-conflicts';
import { groupCommandsByStage } from '../lib/sdlc';
import type { Collection, IDE } from '../../../shared/ipc';
import { StatusDialog } from './StatusDialog';
import { FORMAT_LABELS, folderName } from './format-context';

const INBOX_PAGE_SIZE = 10;
const DEST_DOCKS: IDE[] = ['cursor', 'claude', 'codex', 'copilot', 'agents'];

type PushOutcome =
  | { status: 'loading'; ide: IDE; dest?: string }
  | { status: 'success'; ide: IDE; dest?: string; path?: string }
  | { status: 'error'; ide: IDE; dest?: string; message: string; summary?: string };

type ConflictPrompt = { names: string[] };

function matchesQuery(skillId: string, query: string): boolean {
  const needle = query.trim().toLowerCase();
  return needle.length === 0 || skillId.toLowerCase().includes(needle);
}

function isUnstampedConflict(message: string): boolean {
  return /not generated by skil/i.test(message);
}

function dockPhrase(dock: IDE, dest?: string | null): string {
  return dest ? `${FORMAT_LABELS[dock]} in ${folderName(dest)}` : FORMAT_LABELS[dock];
}

function CollectionDetail({
  collection,
  inbox,
  onChange,
  onDeleted,
}: {
  collection: Collection;
  inbox: string[];
  onChange: () => void;
  onDeleted: () => void;
}) {
  const bridge = useBridge();
  const [error, setError] = useState<string | null>(null);
  const [confirmDelete, setConfirmDelete] = useState(false);
  const [inboxOpen, setInboxOpen] = useState(true);
  const [inboxQuery, setInboxQuery] = useState('');
  const [inboxPage, setInboxPage] = useState(0);
  const [usageCounts, setUsageCounts] = useState<Record<string, number>>({});
  const inboxPickerId = `inbox-picker-${collection.name}`;

  useEffect(() => {
    let cancelled = false;
    void bridge.usage().then((result) => {
      if (cancelled || !result.ok) return;
      const next: Record<string, number> = {};
      for (const row of result.value) {
        next[row.skillId] = row.count;
      }
      setUsageCounts(next);
    });
    return () => {
      cancelled = true;
    };
  }, [bridge, collection.skills]);

  const inboxMatches = useMemo(
    () => inbox.filter((skillId) => matchesQuery(skillId, inboxQuery)),
    [inbox, inboxQuery]
  );
  const inboxPageCount = inboxMatches.length > 0 ? Math.ceil(inboxMatches.length / INBOX_PAGE_SIZE) : 0;
  const safeInboxPage = inboxPageCount === 0 ? 0 : Math.min(inboxPage, inboxPageCount - 1);
  const visibleInbox = inboxMatches.slice(safeInboxPage * INBOX_PAGE_SIZE, (safeInboxPage + 1) * INBOX_PAGE_SIZE);

  async function handleAddFromInbox(skillId: string) {
    setError(null);
    const result = await bridge.addSkill(collection.name, skillId);
    if (!result.ok) {
      setError(result.error.message);
      return;
    }
    onChange();
  }

  async function handleRemoveSkill(skillId: string) {
    setError(null);
    const result = await bridge.removeSkillFromCollection(collection.name, skillId);
    if (!result.ok) {
      setError(result.error.message);
      return;
    }
    onChange();
  }

  async function handleDelete() {
    setError(null);
    const result = await bridge.deleteCollection(collection.name);
    if (!result.ok) {
      setError(result.error.message);
      setConfirmDelete(false);
      return;
    }
    setConfirmDelete(false);
    onDeleted();
  }

  return (
    <section className="detail-panel panel-section" aria-label={`Command ${collection.name} details`}>
      <div className="detail-header">
        <div>
          <p className="eyebrow">Command</p>
          <h2>/{collection.name}</h2>
          <p className="muted-copy">
            {collection.skills.length === 1 ? '1 skill' : `${collection.skills.length} skills`}
          </p>
        </div>
        <div className="detail-actions">
          <button
            type="button"
            onClick={() => setConfirmDelete(true)}
            aria-label={`Delete ${collection.name}`}
            className={`delete-card detail-delete ${FOCUS_RING}`}
          >
            <Trash size={16} weight="regular" aria-hidden="true" />
          </button>
        </div>
      </div>

      {error && (
        <p role="alert" className="rounded-md border border-destructive/40 bg-destructive/10 px-3 py-2 text-sm text-destructive">
          {error}
        </p>
      )}

      <div className="active-skills">
        <div className="subheading">
          <span>Included skills</span>
          <span className="count-pill">{collection.skills.length}</span>
        </div>
        {collection.skills.length === 0 && <p className="muted-copy">No skills in this command yet</p>}
        {collection.skills.map((skillId) => (
          <div className="included-skill" key={skillId}>
            <span>{skillId}</span>
            {usageCounts[skillId] !== undefined && (
              <span className="muted-copy">{usageCounts[skillId]} reads</span>
            )}
            <div className="skill-actions">
              <button
                type="button"
                onClick={() => handleRemoveSkill(skillId)}
                aria-label={`Remove ${skillId}`}
                className={FOCUS_RING}
              >
                <X size={14} weight="regular" />
              </button>
            </div>
          </div>
        ))}
      </div>

      {inbox.length > 0 && (
        <div className="active-skills inbox-picker">
          <button
            type="button"
            className={`inbox-toggle ${FOCUS_RING}`}
            aria-expanded={inboxOpen}
            aria-controls={inboxPickerId}
            aria-label={`From Inbox, ${inbox.length === 1 ? '1 skill' : `${inbox.length} skills`}`}
            onClick={() => setInboxOpen((open) => !open)}
          >
            <span>From Inbox</span>
            <span className="count-pill">{inbox.length}</span>
            <CaretDown className="inbox-caret" size={14} weight="regular" aria-hidden="true" />
          </button>
          <div id={inboxPickerId} hidden={!inboxOpen} className="inbox-picker-list">
            <label className="search-box inbox-filter" htmlFor={`inbox-filter-${collection.name}`}>
              <span className="sr-only">Filter inbox</span>
              <input
                id={`inbox-filter-${collection.name}`}
                value={inboxQuery}
                onChange={(event) => {
                  setInboxQuery(event.target.value);
                  setInboxPage(0);
                }}
                placeholder="Filter inbox"
              />
            </label>
            {visibleInbox.length === 0 ? (
              <p className="muted-copy">No matching skills</p>
            ) : (
              visibleInbox.map((skillId) => {
                const added = collection.skills.includes(skillId);
                return (
                  <div className="library-skill" key={skillId}>
                    <div className="skill-info">
                      <div className="skill-name">{skillId}</div>
                    </div>
                    <button
                      type="button"
                      onClick={() => void handleAddFromInbox(skillId)}
                      aria-label={added ? `Added ${skillId}` : `Add ${skillId} to ${collection.name}`}
                      aria-pressed={added}
                      className={`add-icon-button ${FOCUS_RING}`}
                    >
                      {added ? (
                        <Check size={16} weight="regular" aria-hidden="true" />
                      ) : (
                        <Plus size={16} weight="regular" aria-hidden="true" />
                      )}
                    </button>
                  </div>
                );
              })
            )}
            {inboxPageCount > 1 && (
              <nav aria-label="Inbox pages" className="page-row">
                <button
                  type="button"
                  aria-label="Previous inbox page"
                  disabled={safeInboxPage === 0}
                  onClick={() => setInboxPage(safeInboxPage - 1)}
                  className={`filter ${FOCUS_RING}`}
                >
                  <CaretLeft size={14} weight="regular" aria-hidden="true" />
                </button>
                <span className="page-status">
                  Page {safeInboxPage + 1} of {inboxPageCount}
                </span>
                <button
                  type="button"
                  aria-label="Next inbox page"
                  disabled={safeInboxPage === inboxPageCount - 1}
                  onClick={() => setInboxPage(safeInboxPage + 1)}
                  className={`filter ${FOCUS_RING}`}
                >
                  <CaretRight size={14} weight="regular" aria-hidden="true" />
                </button>
              </nav>
            )}
          </div>
        </div>
      )}

      {confirmDelete && (
        <div className="modal-backdrop" role="presentation" onClick={() => setConfirmDelete(false)}>
          <div
            className="help-modal"
            role="dialog"
            aria-modal="true"
            aria-labelledby="delete-collection-title"
            onClick={(event) => event.stopPropagation()}
          >
            <p className="eyebrow">Commands</p>
            <h2 id="delete-collection-title">Delete {collection.name}?</h2>
            <p className="muted-copy">This cannot be undone.</p>
            <div className="modal-actions">
              <button type="button" className={`outline-button ${FOCUS_RING}`} onClick={() => setConfirmDelete(false)}>
                Cancel
              </button>
              <button type="button" className={`primary-button ${FOCUS_RING}`} onClick={() => void handleDelete()}>
                Delete command
              </button>
            </div>
          </div>
        </div>
      )}
    </section>
  );
}

function selectCollection(event: KeyboardEvent<HTMLLIElement>, name: string, onSelect: (name: string) => void) {
  if (event.key === 'Enter' || event.key === ' ') {
    event.preventDefault();
    onSelect(name);
  }
}

function FormatPicker({ destDock, onDestDock }: { destDock: IDE; onDestDock: (dock: IDE) => void }) {
  const rootRef = useRef<HTMLDivElement>(null);
  const [open, setOpen] = useState(false);
  const menuId = 'export-format-menu';

  useEffect(() => {
    if (!open) return;

    function handlePointerDown(event: PointerEvent) {
      if (rootRef.current && !rootRef.current.contains(event.target as Node)) {
        setOpen(false);
      }
    }

    function handleKey(event: KeyboardEvent) {
      if (event.key === 'Escape') {
        event.preventDefault();
        setOpen(false);
      }
    }

    document.addEventListener('pointerdown', handlePointerDown);
    document.addEventListener('keydown', handleKey);
    return () => {
      document.removeEventListener('pointerdown', handlePointerDown);
      document.removeEventListener('keydown', handleKey);
    };
  }, [open]);

  return (
    <div className="format-picker" ref={rootRef}>
      <button
        type="button"
        onClick={() => setOpen((value) => !value)}
        aria-haspopup="menu"
        aria-expanded={open}
        aria-controls={open ? menuId : undefined}
        aria-label={`Pick format: ${FORMAT_LABELS[destDock]}`}
        className={`format-picker-trigger ${FOCUS_RING}`}
      >
        <span>{FORMAT_LABELS[destDock]}</span>
        <CaretDown size={12} weight="regular" aria-hidden="true" />
      </button>
      {open && (
        <div id={menuId} role="menu" aria-label="Pick format" className="skill-install-menu import-copy-menu">
          {DEST_DOCKS.map((dock) => (
            <button
              key={dock}
              type="button"
              role="menuitemradio"
              aria-checked={dock === destDock}
              className={FOCUS_RING}
              onClick={() => {
                onDestDock(dock);
                setOpen(false);
              }}
            >
              {FORMAT_LABELS[dock]}
            </button>
          ))}
        </div>
      )}
    </div>
  );
}

function CollectionsPanel({
  children,
  destDock,
  onDestDock,
  onExport,
  isBusy,
  canExport,
}: {
  children: ReactNode;
  destDock: IDE;
  onDestDock: (dock: IDE) => void;
  onExport: () => void;
  isBusy: boolean;
  canExport: boolean;
}) {
  return (
    <section className="collections-panel panel-section">
      <div className="section-heading">
        <div>
          <p className="eyebrow">Workspace</p>
          <h1>Commands</h1>
          <p className="workspace-lede">Named SDLC knobs. File inbox skills onto them, then export to a dock.</p>
        </div>
        <div className="library-heading-actions">
          <FormatPicker destDock={destDock} onDestDock={onDestDock} />
          <button
            type="button"
            onClick={onExport}
            disabled={!canExport || isBusy}
            aria-busy={isBusy || undefined}
            className={`import-button ${FOCUS_RING}`}
          >
            {isBusy ? (
              <CircleNotch size={16} weight="regular" className="spin" aria-hidden="true" />
            ) : (
              <DownloadSimple size={16} weight="regular" aria-hidden="true" />
            )}
            Export
          </button>
        </div>
      </div>
      {children}
    </section>
  );
}

function ConflictDialog({
  title,
  body,
  names,
  confirmLabel,
  onCancel,
  onConfirm,
}: {
  title: string;
  body: string;
  names: string[];
  confirmLabel: string;
  onCancel: () => void;
  onConfirm: () => void;
}) {
  return (
    <div className="modal-backdrop" role="presentation" onClick={onCancel}>
      <div
        className="help-modal"
        role="dialog"
        aria-modal="true"
        aria-labelledby="conflict-title"
        onClick={(event) => event.stopPropagation()}
      >
        <p className="eyebrow">Sync</p>
        <h2 id="conflict-title">{title}</h2>
        <p className="muted-copy">{body}</p>
        {names.length > 0 && (
          <ul className="conflict-list" aria-label="Conflicting commands">
            {names.map((name) => (
              <li key={name}>/{name}</li>
            ))}
          </ul>
        )}
        <div className="modal-actions">
          <button type="button" className={`outline-button ${FOCUS_RING}`} onClick={onCancel}>
            Cancel
          </button>
          <button type="button" className={`primary-button ${FOCUS_RING}`} onClick={onConfirm}>
            {confirmLabel}
          </button>
        </div>
      </div>
    </div>
  );
}

export default function CollectionList({
  children,
  onProjectBound,
}: {
  children?: ReactNode;
  onProjectBound?: (root: string) => void;
}) {
  const bridge = useBridge();
  const [collections, setCollections] = useState<Collection[] | null>(null);
  const [inbox, setInbox] = useState<string[]>([]);
  const [selectedName, setSelectedName] = useState<string | null>(null);
  const [destDock, setDestDock] = useState<IDE>('cursor');
  const [exportOutcome, setExportOutcome] = useState<PushOutcome | null>(null);
  const [conflict, setConflict] = useState<ConflictPrompt | null>(null);
  const [exportDest, setExportDest] = useState<string | undefined>();
  const refreshId = useRef(0);
  const isBusy = exportOutcome?.status === 'loading';

  const refresh = useCallback(async () => {
    const id = ++refreshId.current;
    const [nextInbox, next] = await Promise.all([bridge.listInbox(), bridge.listCollections()]);
    if (id !== refreshId.current) return;
    setInbox(nextInbox);
    setCollections(next);
    setSelectedName((current) => {
      if (current && next.some((collection) => collection.name === current)) return current;
      return next[0]?.name ?? null;
    });
  }, [bridge]);

  useEffect(() => {
    void refresh();
  }, [refresh]);

  useEffect(() => {
    return bridge.onScan(() => {
      void refresh();
    });
  }, [bridge, refresh]);

  async function bindPickedFolder(root: string | null, dest: string | undefined) {
    if (root || !dest) return;
    const bound = await bridge.bindProjectFolder(dest);
    if (!bound) return;
    onProjectBound?.(bound);
    await bridge.scan();
  }

  async function pickDest(
    replace: boolean,
    cached: string | undefined,
    setCached: (path: string) => void
  ): Promise<{ root: string | null; dest: string | undefined; target: string | undefined } | null> {
    const root = await bridge.getProjectRoot();
    let dest: string | undefined;
    if (!root) {
      dest = replace ? cached : undefined;
      if (dest === undefined) {
        const picked = await bridge.pickDestinationFolder();
        if (picked === null) return null;
        dest = picked;
        setCached(picked);
      }
    }
    return { root, dest, target: dest ?? root ?? undefined };
  }

  async function handleExport(replace?: boolean) {
    setConflict(null);
    const picked = await pickDest(replace === true, exportDest, setExportDest);
    if (!picked) return;
    const { root, dest, target } = picked;
    setExportOutcome({ status: 'loading', ide: destDock, dest: target });
    const result = await bridge.exportAll(destDock, {
      ...(replace ? { replace: true } : {}),
      ...(dest ? { dest } : {}),
    });

    if (!result.ok) {
      if (isUnstampedConflict(result.error.message)) {
        setExportOutcome(null);
        setConflict({ names: parseConflictedCommandNames(result.error.message) });
        return;
      }
      setExportDest(undefined);
      setExportOutcome({ status: 'error', ide: destDock, dest: target, message: result.error.message });
      await bindPickedFolder(root, dest);
      return;
    }
    setExportDest(undefined);
    if (result.value.failures.length > 0) {
      setExportOutcome({
        status: 'error',
        ide: destDock,
        dest: target,
        summary: `Exported the command files, but some skills did not deploy to ${dockPhrase(destDock, target)}`,
        message: result.value.failures.join('\n'),
      });
      await bindPickedFolder(root, dest);
      return;
    }
    setExportOutcome({
      status: 'success',
      ide: destDock,
      dest: target,
      path: result.value.succeeded[0],
    });
    await bindPickedFolder(root, dest);
  }

  const createSlot = isValidElement(children)
    ? cloneElement(children as ReactElement<{ onCreated?: (collection: Collection) => void }>, {
        onCreated: () => {
          void refresh();
        },
      })
    : children;

  const selected = collections ? (collections.find((collection) => collection.name === selectedName) ?? null) : null;
  const hasCommands = (collections?.length ?? 0) > 0;

  return (
    <>
      <CollectionsPanel
        destDock={destDock}
        onDestDock={setDestDock}
        onExport={() => void handleExport()}
        isBusy={isBusy}
        canExport={hasCommands}
      >
        {collections === null ? null : collections.length === 0 ? (
          <p className="muted-copy">No commands yet</p>
        ) : (
          <div className="command-stages">
            {groupCommandsByStage(collections).map((stage) => (
              <div className="command-stage" key={stage.key}>
                {stage.label && <p className="stage-label">{stage.label}</p>}
                <ul className="collection-list">
                  {stage.commands.map((collection) => (
                    <li
                      key={collection.name}
                      aria-label={`Command ${collection.name}`}
                      aria-current={collection.name === selectedName ? 'true' : undefined}
                      className={`collection-card ${collection.name === selectedName ? 'selected' : ''}`}
                      tabIndex={0}
                      onClick={() => setSelectedName(collection.name)}
                      onKeyDown={(event) => selectCollection(event, collection.name, setSelectedName)}
                    >
                      <div className="card-title">
                        <span>/{collection.name}</span>
                      </div>
                      <div className="skill-count">
                        <span>
                          {collection.skills.length} {collection.skills.length === 1 ? 'skill' : 'skills'}
                        </span>
                      </div>
                    </li>
                  ))}
                </ul>
              </div>
            ))}
          </div>
        )}
        {createSlot}
      </CollectionsPanel>
      {selected && (
        <CollectionDetail
          key={selected.name}
          collection={selected}
          inbox={inbox}
          onChange={refresh}
          onDeleted={refresh}
        />
      )}
      {exportOutcome && (
        <StatusDialog
          eyebrow="Export"
          title={
            exportOutcome.status === 'loading'
              ? 'Exporting…'
              : exportOutcome.status === 'success'
                ? 'Exported'
                : 'Export failed'
          }
          kind={exportOutcome.status}
          errorDetail={exportOutcome.status === 'error' ? exportOutcome.message : undefined}
          closeLabel="Close export status"
          onClose={() => setExportOutcome(null)}
        >
          {exportOutcome.status === 'loading' && (
            <p role="status" className="muted-copy">
              Exporting all commands to {dockPhrase(exportOutcome.ide, exportOutcome.dest)}
            </p>
          )}
          {exportOutcome.status === 'success' && (
            <>
              <p className="status-copy-success">{`Exported all commands to ${dockPhrase(exportOutcome.ide, exportOutcome.dest)}`}</p>
              {exportOutcome.path && <p className="status-path">{exportOutcome.path}</p>}
            </>
          )}
          {exportOutcome.status === 'error' && (
            <p role="alert" className="muted-copy text-destructive">
              {exportOutcome.summary ??
                `Could not export commands to ${dockPhrase(exportOutcome.ide, exportOutcome.dest)}`}
            </p>
          )}
        </StatusDialog>
      )}
      {conflict && (
        <ConflictDialog
          title="Replace existing commands?"
          body="These command files already exist and were not generated by skil. Replace them with our command templates?"
          names={conflict.names}
          confirmLabel="Replace"
          onCancel={() => setConflict(null)}
          onConfirm={() => void handleExport(true)}
        />
      )}
    </>
  );
}
