import { useCallback, useEffect, useMemo, useState, type KeyboardEvent, type ReactNode } from 'react';
import { CaretDown, CaretLeft, CaretRight, Check, CircleNotch, DownloadSimple, Plus, Trash, X } from '@phosphor-icons/react';
import { useBridge } from '../bridge-context';
import { FOCUS_RING } from '../lib/focus-ring';
import { groupCommandsByStage } from '../lib/sdlc';
import type { Collection, IDE } from '../../../shared/ipc';
import { targetPhrase } from './InstallSkill';
import { FormatSelect } from './FormatSelect';
import { StatusDialog } from './StatusDialog';

const INBOX_PAGE_SIZE = 10;

type ExportOutcome =
  | { status: 'loading'; ide: IDE; dest?: string }
  | { status: 'success'; ide: IDE; dest?: string; path?: string }
  | { status: 'error'; ide: IDE; dest?: string; message: string; summary?: string };

function matchesQuery(skillId: string, query: string): boolean {
  const needle = query.trim().toLowerCase();
  return needle.length === 0 || skillId.toLowerCase().includes(needle);
}

function isUnstampedConflict(message: string): boolean {
  return /not generated by skil/i.test(message);
}

function CollectionDetail({
  collection,
  inbox,
  onChange,
  onDeleted,
}: {
  collection: Collection;
  inbox: string[];
  onChange: () => void;
  onDeleted: () => void;
}) {
  const bridge = useBridge();
  const [error, setError] = useState<string | null>(null);
  const [exportIde, setExportIde] = useState<IDE>('cursor');
  const [exportOutcome, setExportOutcome] = useState<ExportOutcome | null>(null);
  const [confirmDelete, setConfirmDelete] = useState(false);
  const [confirmReplace, setConfirmReplace] = useState(false);
  const [inboxOpen, setInboxOpen] = useState(true);
  const [inboxQuery, setInboxQuery] = useState('');
  const [inboxPage, setInboxPage] = useState(0);
  const [exportDest, setExportDest] = useState<string | undefined>();
  const inboxPickerId = `inbox-picker-${collection.name}`;
  const isExporting = exportOutcome?.status === 'loading';

  const inboxMatches = useMemo(
    () => inbox.filter((skillId) => matchesQuery(skillId, inboxQuery)),
    [inbox, inboxQuery]
  );
  const inboxPageCount = inboxMatches.length > 0 ? Math.ceil(inboxMatches.length / INBOX_PAGE_SIZE) : 0;
  const safeInboxPage = inboxPageCount === 0 ? 0 : Math.min(inboxPage, inboxPageCount - 1);
  const visibleInbox = inboxMatches.slice(safeInboxPage * INBOX_PAGE_SIZE, (safeInboxPage + 1) * INBOX_PAGE_SIZE);

  async function handleAddFromInbox(skillId: string) {
    setError(null);
    const result = await bridge.addSkill(collection.name, skillId);
    if (!result.ok) {
      setError(result.error.message);
      return;
    }
    onChange();
  }

  async function handleRemoveSkill(skillId: string) {
    setError(null);
    const result = await bridge.removeSkillFromCollection(collection.name, skillId);
    if (!result.ok) {
      setError(result.error.message);
      return;
    }
    onChange();
  }

  async function handleExport(replace?: boolean) {
    setError(null);
    const root = await bridge.getProjectRoot();
    let dest: string | undefined;
    if (!root) {
      dest = replace ? exportDest : undefined;
      if (dest === undefined) {
        const picked = await bridge.pickDestinationFolder();
        if (picked === null) return;
        dest = picked;
        setExportDest(picked);
      }
    }
    const target = dest ?? root ?? undefined;
    if (replace) setConfirmReplace(false);
    setExportOutcome({ status: 'loading', ide: exportIde, dest: target });
    const result = await bridge.exportCommand(collection.name, exportIde, {
      ...(replace ? { replace: true } : {}),
      ...(dest ? { dest } : {}),
    });

    if (!result.ok) {
      if (isUnstampedConflict(result.error.message)) {
        setExportOutcome(null);
        setConfirmReplace(true);
        return;
      }
      setExportDest(undefined);
      setExportOutcome({ status: 'error', ide: exportIde, dest: target, message: result.error.message });
      return;
    }
    setExportDest(undefined);
    setConfirmReplace(false);
    if (result.value.failures.length > 0) {
      setExportOutcome({
        status: 'error',
        ide: exportIde,
        dest: target,
        summary: `Exported the command file, but some skills did not deploy to ${targetPhrase(exportIde, target)}`,
        message: result.value.failures.join('\n'),
      });
      return;
    }
    setExportOutcome({
      status: 'success',
      ide: exportIde,
      dest: target,
      path: result.value.succeeded[0],
    });
  }

  async function handleDelete() {
    setError(null);
    const result = await bridge.deleteCollection(collection.name);
    if (!result.ok) {
      setError(result.error.message);
      setConfirmDelete(false);
      return;
    }
    setConfirmDelete(false);
    onDeleted();
  }

  return (
    <section className="detail-panel panel-section" aria-label={`Command ${collection.name} details`}>
      <div className="detail-header">
        <div>
          <p className="eyebrow">Command</p>
          <h2>/{collection.name}</h2>
          <p className="muted-copy">
            {collection.skills.length === 1 ? '1 skill' : `${collection.skills.length} skills`}
          </p>
        </div>
        <div className="detail-actions">
          <button
            type="button"
            onClick={() => setConfirmDelete(true)}
            aria-label={`Delete ${collection.name}`}
            className={`delete-card detail-delete ${FOCUS_RING}`}
          >
            <Trash size={16} weight="regular" aria-hidden="true" />
          </button>
          <button
            type="button"
            onClick={() => void handleExport()}
            disabled={isExporting}
            aria-label={`Export ${collection.name}`}
            aria-busy={isExporting || undefined}
            className={`export-button ${FOCUS_RING}`}
          >
            <span>Export</span>
            {isExporting ? (
              <CircleNotch size={16} weight="regular" className="spin" aria-hidden="true" />
            ) : (
              <DownloadSimple size={16} weight="regular" aria-hidden="true" />
            )}
          </button>
        </div>
      </div>

      {error && (
        <p role="alert" className="rounded-md border border-destructive/40 bg-destructive/10 px-3 py-2 text-sm text-destructive">
          {error}
        </p>
      )}

      <div className="target-row">
        <span>Format</span>
        <FormatSelect
          id={`export-ide-${collection.name}`}
          label={`Export ${collection.name} to`}
          value={exportIde}
          disabled={isExporting}
          onChange={setExportIde}
        />
      </div>

      <div className="active-skills">
        <div className="subheading">
          <span>Included skills</span>
          <span className="count-pill">{collection.skills.length}</span>
        </div>
        {collection.skills.length === 0 && <p className="muted-copy">No skills in this command yet</p>}
        {collection.skills.map((skillId) => (
          <div className="included-skill" key={skillId}>
            <span>{skillId}</span>
            <div className="skill-actions">
              <button
                type="button"
                onClick={() => handleRemoveSkill(skillId)}
                aria-label={`Remove ${skillId}`}
                className={FOCUS_RING}
              >
                <X size={14} weight="regular" />
              </button>
            </div>
          </div>
        ))}
      </div>

      {inbox.length > 0 && (
        <div className="active-skills inbox-picker">
          <button
            type="button"
            className={`inbox-toggle ${FOCUS_RING}`}
            aria-expanded={inboxOpen}
            aria-controls={inboxPickerId}
            aria-label={`From Inbox, ${inbox.length === 1 ? '1 skill' : `${inbox.length} skills`}`}
            onClick={() => setInboxOpen((open) => !open)}
          >
            <span>From Inbox</span>
            <span className="count-pill">{inbox.length}</span>
            <CaretDown className="inbox-caret" size={14} weight="regular" aria-hidden="true" />
          </button>
          <div id={inboxPickerId} hidden={!inboxOpen} className="inbox-picker-list">
            <label className="search-box inbox-filter" htmlFor={`inbox-filter-${collection.name}`}>
              <span className="sr-only">Filter inbox</span>
              <input
                id={`inbox-filter-${collection.name}`}
                value={inboxQuery}
                onChange={(event) => {
                  setInboxQuery(event.target.value);
                  setInboxPage(0);
                }}
                placeholder="Filter inbox"
              />
            </label>
            {visibleInbox.length === 0 ? (
              <p className="muted-copy">No matching skills</p>
            ) : (
              visibleInbox.map((skillId) => {
                const added = collection.skills.includes(skillId);
                return (
                  <div className="library-skill" key={skillId}>
                    <div className="skill-info">
                      <div className="skill-name">{skillId}</div>
                    </div>
                    <button
                      type="button"
                      onClick={() => void handleAddFromInbox(skillId)}
                      aria-label={added ? `Added ${skillId}` : `Add ${skillId} to ${collection.name}`}
                      aria-pressed={added}
                      className={`add-icon-button ${FOCUS_RING}`}
                    >
                      {added ? (
                        <Check size={16} weight="regular" aria-hidden="true" />
                      ) : (
                        <Plus size={16} weight="regular" aria-hidden="true" />
                      )}
                    </button>
                  </div>
                );
              })
            )}
            {inboxPageCount > 1 && (
              <nav aria-label="Inbox pages" className="page-row">
                <button
                  type="button"
                  aria-label="Previous inbox page"
                  disabled={safeInboxPage === 0}
                  onClick={() => setInboxPage(safeInboxPage - 1)}
                  className={`filter ${FOCUS_RING}`}
                >
                  <CaretLeft size={14} weight="regular" aria-hidden="true" />
                </button>
                <span className="page-status">
                  Page {safeInboxPage + 1} of {inboxPageCount}
                </span>
                <button
                  type="button"
                  aria-label="Next inbox page"
                  disabled={safeInboxPage === inboxPageCount - 1}
                  onClick={() => setInboxPage(safeInboxPage + 1)}
                  className={`filter ${FOCUS_RING}`}
                >
                  <CaretRight size={14} weight="regular" aria-hidden="true" />
                </button>
              </nav>
            )}
          </div>
        </div>
      )}

      {exportOutcome && (
        <StatusDialog
          eyebrow="Export"
          title={
            exportOutcome.status === 'loading'
              ? 'Exporting…'
              : exportOutcome.status === 'success'
                ? 'Exported'
                : 'Export failed'
          }
          kind={exportOutcome.status}
          errorDetail={exportOutcome.status === 'error' ? exportOutcome.message : undefined}
          closeLabel="Close export status"
          onClose={() => setExportOutcome(null)}
        >
          {exportOutcome.status === 'loading' && (
            <p role="status" className="muted-copy">
              Exporting {collection.name} to {targetPhrase(exportOutcome.ide, exportOutcome.dest)}
            </p>
          )}
          {exportOutcome.status === 'success' && (
            <>
              <p className="status-copy-success">{`Exported ${collection.name} to ${targetPhrase(exportOutcome.ide, exportOutcome.dest)}`}</p>
              {exportOutcome.path && <p className="status-path">{exportOutcome.path}</p>}
            </>
          )}
          {exportOutcome.status === 'error' && (
            <p role="alert" className="muted-copy text-destructive">
              {exportOutcome.summary ??
                `Could not export ${collection.name} to ${targetPhrase(exportOutcome.ide, exportOutcome.dest)}`}
            </p>
          )}
        </StatusDialog>
      )}

      {confirmReplace && (
        <div className="modal-backdrop" role="presentation" onClick={() => setConfirmReplace(false)}>
          <div
            className="help-modal"
            role="dialog"
            aria-modal="true"
            aria-labelledby="replace-export-title"
            onClick={(event) => event.stopPropagation()}
          >
            <p className="eyebrow">Export</p>
            <h2 id="replace-export-title">Replace existing file?</h2>
            <p className="muted-copy">
              This file exists and was not generated by skil. Replace it with our command template?
            </p>
            <div className="modal-actions">
              <button type="button" className={`outline-button ${FOCUS_RING}`} onClick={() => setConfirmReplace(false)}>
                Cancel
              </button>
              <button type="button" className={`primary-button ${FOCUS_RING}`} onClick={() => void handleExport(true)}>
                Replace
              </button>
            </div>
          </div>
        </div>
      )}

      {confirmDelete && (
        <div className="modal-backdrop" role="presentation" onClick={() => setConfirmDelete(false)}>
          <div
            className="help-modal"
            role="dialog"
            aria-modal="true"
            aria-labelledby="delete-collection-title"
            onClick={(event) => event.stopPropagation()}
          >
            <p className="eyebrow">Commands</p>
            <h2 id="delete-collection-title">Delete {collection.name}?</h2>
            <p className="muted-copy">This cannot be undone.</p>
            <div className="modal-actions">
              <button type="button" className={`outline-button ${FOCUS_RING}`} onClick={() => setConfirmDelete(false)}>
                Cancel
              </button>
              <button type="button" className={`primary-button ${FOCUS_RING}`} onClick={() => void handleDelete()}>
                Delete command
              </button>
            </div>
          </div>
        </div>
      )}
    </section>
  );
}

function selectCollection(event: KeyboardEvent<HTMLLIElement>, name: string, onSelect: (name: string) => void) {
  if (event.key === 'Enter' || event.key === ' ') {
    event.preventDefault();
    onSelect(name);
  }
}

function CollectionsPanel({ children }: { children: ReactNode }) {
  return (
    <section className="collections-panel panel-section">
      <div className="section-heading">
        <div>
          <p className="eyebrow">Workspace</p>
          <h1>Commands</h1>
          <p className="workspace-lede">Named SDLC knobs. File inbox skills onto them, then export.</p>
        </div>
      </div>
      {children}
    </section>
  );
}

export default function CollectionList({ children }: { children?: ReactNode }) {
  const bridge = useBridge();
  const [collections, setCollections] = useState<Collection[] | null>(null);
  const [inbox, setInbox] = useState<string[]>([]);
  const [selectedName, setSelectedName] = useState<string | null>(null);

  const refresh = useCallback(async () => {
    const [next, nextInbox] = await Promise.all([bridge.listCollections(), bridge.listInbox()]);
    setCollections(next);
    setInbox(nextInbox);
    setSelectedName((current) => {
      if (current && next.some((collection) => collection.name === current)) return current;
      return next[0]?.name ?? null;
    });
  }, [bridge]);

  useEffect(() => {
    void refresh();
  }, [refresh]);

  if (collections === null) {
    return <CollectionsPanel>{children}</CollectionsPanel>;
  }

  const selected = collections.find((collection) => collection.name === selectedName) ?? null;

  return (
    <>
      <CollectionsPanel>
        {collections.length === 0 ? (
          <p className="muted-copy">No commands yet</p>
        ) : (
          <div className="command-stages">
            {groupCommandsByStage(collections).map((stage) => (
              <div className="command-stage" key={stage.key}>
                {stage.label && <p className="stage-label">{stage.label}</p>}
                <ul className="collection-list">
                  {stage.commands.map((collection) => (
                    <li
                      key={collection.name}
                      aria-label={`Command ${collection.name}`}
                      aria-current={collection.name === selectedName ? 'true' : undefined}
                      className={`collection-card ${collection.name === selectedName ? 'selected' : ''}`}
                      tabIndex={0}
                      onClick={() => setSelectedName(collection.name)}
                      onKeyDown={(event) => selectCollection(event, collection.name, setSelectedName)}
                    >
                      <div className="card-title">
                        <span>/{collection.name}</span>
                      </div>
                      <div className="skill-count">
                        <span>
                          {collection.skills.length} {collection.skills.length === 1 ? 'skill' : 'skills'}
                        </span>
                      </div>
                    </li>
                  ))}
                </ul>
              </div>
            ))}
          </div>
        )}
        {children}
      </CollectionsPanel>
      {selected && (
        <CollectionDetail
          key={selected.name}
          collection={selected}
          inbox={inbox}
          onChange={refresh}
          onDeleted={refresh}
        />
      )}
    </>
  );
}
